/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import controlador.ClasseGeral;
import controlador.ControleAluno;
import controlador.ControleCmei;
import controlador.ControleEscola;
import controlador.ControleOutro;
import controlador.ControleVersao;
import controlador.FixedLengthDocument;
import controlador.Formatos;
import dao.DAO;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Aluno;
import modelo.Cmei;
import modelo.Endereco;
import modelo.Escola;
import modelo.Outro;
import modelo.Permissoes;

/**
 *
 * @author luizam
 */
public class JdBuscaEndereco extends javax.swing.JDialog {
    
    private static ControleVersao versao = new ControleVersao();
    private Aluno aluno;
    private Cmei cmei;
    private ClasseGeral classeGeral;
    private ControleAluno controleAluno;
    private ControleCmei controleCmei;
    private ControleEscola controleEscola;
    private ControleOutro controleOutro;
    private DAO dao;
    private DefaultTableModel modelo;
    private Endereco endereco;
    private Escola escola;
    private Formatos formatos = new Formatos();
    private Outro outro;
    
    private int codigoUsuario;
    private int codigoAluno = 0;
    private int codigoCmei = 0;
    private int codigoEscola = 0;
    private int codigoOutro = 0;
    
    /**
     * Creates new form JdBuscaEndereco
     */
    public JdBuscaEndereco(java.awt.Frame parent, boolean modal) {
        super(parent, "m2 - Busca Endereço - " + versao.getVersao() + " - " + versao.getAno(), modal);
        initComponents();

        //Altera icone na barra de titulo
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage("C:/m2GestaoClinicas/imagens/logom2clinicas.jpg");
        this.setIconImage(img);

        //centraliza tela
        setSize(getWidth(), getHeight());
        setLocationRelativeTo(null);

        try {
            jftfBuscaCepEndereco.setFormatterFactory(formatos.getFormatoCep());
        } catch (ParseException ex) {
            Logger.getLogger(JdBuscaEndereco.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Não foi possivel formatar campo de CPF ou/e RG, \n Contate o Administrador!", "Erro", 0, null);
        }
        
        setNumeroCaracteres();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBuscaEnderecoFundo = new javax.swing.JPanel();
        jpBuscaEndereco = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbBuscaEndereco = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfBuscaEndereco = new javax.swing.JTextField();
        jcbBuscaTipoEndereco = new javax.swing.JComboBox();
        jtfBuscaNumeroEndereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfBuscaCidadeEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbBuscaUfEndereco = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jftfBuscaCepEndereco = new javax.swing.JFormattedTextField();
        jpBotoes = new javax.swing.JPanel();
        jbBuscaFechar = new javax.swing.JButton();
        jbBuscaEnviarDados = new javax.swing.JButton();
        jbBuscaCancelar = new javax.swing.JButton();
        jbBuscaPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpBuscaEnderecoFundo.setBackground(new java.awt.Color(255, 255, 255));

        jpBuscaEndereco.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jtbBuscaEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo Endereço", "Endereço", "Número", "Bairro", "Cidade", "UF", "Código"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbBuscaEndereco);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Tipo Endereço: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Endereço: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Número: ");

        jtfBuscaEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfBuscaEndereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfBuscaEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBuscaEnderecoFocusLost(evt);
            }
        });

        jcbBuscaTipoEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbBuscaTipoEndereco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "RESIDENCIAL", "COMERCIAL", "PÚBLICO" }));
        jcbBuscaTipoEndereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtfBuscaNumeroEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfBuscaNumeroEndereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfBuscaNumeroEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBuscaNumeroEnderecoFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Cidade: ");

        jtfBuscaCidadeEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfBuscaCidadeEndereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfBuscaCidadeEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBuscaCidadeEnderecoFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("UF: ");

        jcbBuscaUfEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbBuscaUfEndereco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PE", "PR", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jcbBuscaUfEndereco.setSelectedIndex(16);
        jcbBuscaUfEndereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("CEP: ");

        jftfBuscaCepEndereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jpBuscaEnderecoLayout = new javax.swing.GroupLayout(jpBuscaEndereco);
        jpBuscaEndereco.setLayout(jpBuscaEnderecoLayout);
        jpBuscaEnderecoLayout.setHorizontalGroup(
            jpBuscaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscaEnderecoLayout.createSequentialGroup()
                .addGroup(jpBuscaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBuscaEnderecoLayout.createSequentialGroup()
                        .addGroup(jpBuscaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpBuscaEnderecoLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBuscaEnderecoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jpBuscaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpBuscaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbBuscaTipoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpBuscaEnderecoLayout.createSequentialGroup()
                                .addGroup(jpBuscaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfBuscaCidadeEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfBuscaEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpBuscaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpBuscaEnderecoLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfBuscaNumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpBuscaEnderecoLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbBuscaUfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jftfBuscaCepEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpBuscaEnderecoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpBuscaEnderecoLayout.setVerticalGroup(
            jpBuscaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBuscaEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBuscaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbBuscaTipoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBuscaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfBuscaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtfBuscaNumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBuscaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfBuscaCidadeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jcbBuscaUfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBuscaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jftfBuscaCepEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpBotoes.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jbBuscaFechar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbBuscaFechar.setMnemonic('f');
        jbBuscaFechar.setText("Fechar");
        jbBuscaFechar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscaFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaFecharActionPerformed(evt);
            }
        });

        jbBuscaEnviarDados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbBuscaEnviarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Enviar.png"))); // NOI18N
        jbBuscaEnviarDados.setMnemonic('d');
        jbBuscaEnviarDados.setText("Enviar Dados");
        jbBuscaEnviarDados.setToolTipText("Envia os dados do item selecinado para tela de cadastro!");
        jbBuscaEnviarDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscaEnviarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaEnviarDadosActionPerformed(evt);
            }
        });

        jbBuscaCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbBuscaCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jbBuscaCancelar.setMnemonic('z');
        jbBuscaCancelar.setText("Cancelar");
        jbBuscaCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaCancelarActionPerformed(evt);
            }
        });

        jbBuscaPesquisar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbBuscaPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jbBuscaPesquisar.setMnemonic('p');
        jbBuscaPesquisar.setText("Pesquisar");
        jbBuscaPesquisar.setToolTipText("Pesquisa e exibe dados na tabela!");
        jbBuscaPesquisar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesLayout = new javax.swing.GroupLayout(jpBotoes);
        jpBotoes.setLayout(jpBotoesLayout);
        jpBotoesLayout.setHorizontalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbBuscaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscaEnviarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscaFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpBotoesLayout.setVerticalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscaFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscaEnviarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpBuscaEnderecoFundoLayout = new javax.swing.GroupLayout(jpBuscaEnderecoFundo);
        jpBuscaEnderecoFundo.setLayout(jpBuscaEnderecoFundoLayout);
        jpBuscaEnderecoFundoLayout.setHorizontalGroup(
            jpBuscaEnderecoFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpBuscaEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpBuscaEnderecoFundoLayout.setVerticalGroup(
            jpBuscaEnderecoFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscaEnderecoFundoLayout.createSequentialGroup()
                .addComponent(jpBuscaEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBuscaEnderecoFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBuscaEnderecoFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfBuscaEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscaEnderecoFocusLost
        jtfBuscaEndereco.setText(jtfBuscaEndereco.getText().toUpperCase());
    }//GEN-LAST:event_jtfBuscaEnderecoFocusLost

    private void jtfBuscaNumeroEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscaNumeroEnderecoFocusLost
        jtfBuscaNumeroEndereco.setText(jtfBuscaNumeroEndereco.getText().toUpperCase());
    }//GEN-LAST:event_jtfBuscaNumeroEnderecoFocusLost

    private void jtfBuscaCidadeEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBuscaCidadeEnderecoFocusLost
        jtfBuscaCidadeEndereco.setText(jtfBuscaCidadeEndereco.getText().toUpperCase());
    }//GEN-LAST:event_jtfBuscaCidadeEnderecoFocusLost

    private void jbBuscaFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaFecharActionPerformed
        fechar();
    }//GEN-LAST:event_jbBuscaFecharActionPerformed

    private void jbBuscaEnviarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaEnviarDadosActionPerformed
        buscaDados();
        fechar();
    }//GEN-LAST:event_jbBuscaEnviarDadosActionPerformed

    private void jbBuscaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_jbBuscaCancelarActionPerformed

    private void jbBuscaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaPesquisarActionPerformed
        pesquisar();
    }//GEN-LAST:event_jbBuscaPesquisarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fechar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdBuscaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdBuscaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdBuscaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdBuscaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdBuscaEndereco dialog = new JdBuscaEndereco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscaCancelar;
    private javax.swing.JButton jbBuscaEnviarDados;
    private javax.swing.JButton jbBuscaFechar;
    private javax.swing.JButton jbBuscaPesquisar;
    private javax.swing.JComboBox jcbBuscaTipoEndereco;
    private javax.swing.JComboBox jcbBuscaUfEndereco;
    private javax.swing.JFormattedTextField jftfBuscaCepEndereco;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpBuscaEndereco;
    private javax.swing.JPanel jpBuscaEnderecoFundo;
    private javax.swing.JTable jtbBuscaEndereco;
    private javax.swing.JTextField jtfBuscaCidadeEndereco;
    private javax.swing.JTextField jtfBuscaEndereco;
    private javax.swing.JTextField jtfBuscaNumeroEndereco;
    // End of variables declaration//GEN-END:variables

//Outros Metodos ===========================================================================================================================================
    public void fechar() {

        cancelar();
        this.dispose();

    }

    public void cancelar() {

        iniciaTabela();

        jtfBuscaCidadeEndereco.setText("");
        jtfBuscaEndereco.setText("");
        jtfBuscaNumeroEndereco.setText("");
        jftfBuscaCepEndereco.setText("     -   ");
        jcbBuscaTipoEndereco.setSelectedIndex(0);
        jcbBuscaUfEndereco.setSelectedIndex(16);
        
        classeGeral = null;
        
        modelo.setRowCount(0);

    }

    public void pesquisar() {

        iniciaTabela();
        iniciaDao();
        Endereco end;
        List listaEndereco = new ArrayList();
        String cepEndereco;
        String nomeAlunoCmeiEscolaOutro = "";
        String tipoEndereco;

        final TableRowSorter<TableModel> tabelaSorter = new TableRowSorter<TableModel>(modelo);
        jtbBuscaEndereco.setRowSorter(tabelaSorter);
        
        if (jftfBuscaCepEndereco.getText().equals("     -   ")) {
            cepEndereco = "";
        } else {
            cepEndereco = jftfBuscaCepEndereco.getText();
        }
        
        if (jcbBuscaTipoEndereco.getSelectedIndex() == 0) {
            tipoEndereco = "";
        } else {
            tipoEndereco = jcbBuscaTipoEndereco.getSelectedItem().toString();
        }

        listaEndereco = dao.listarEnderecos(tipoEndereco, jtfBuscaEndereco.getText(), jtfBuscaNumeroEndereco.getText(), jtfBuscaCidadeEndereco.getText(), 
                jcbBuscaUfEndereco.getSelectedItem().toString(), cepEndereco, codigoAluno, codigoCmei, codigoEscola, codigoOutro);

        modelo.setRowCount(0);

        for (int i = 0; listaEndereco.size() > i; i++) {

            end = (Endereco) listaEndereco.get(i);

            switch(end.getTipoCadastro()) {
                
                case "ALUNO":
                    iniciaAluno();
                    aluno = end.getAluno();
                    nomeAlunoCmeiEscolaOutro = aluno.getNomeAluno();
                    break;
                
                case "CMEI":
                    iniciaCmei();
                    cmei = end.getCmei();
                    nomeAlunoCmeiEscolaOutro = cmei.getNomeCmei();
                    break;
                
                case "ESCOLA":
                    iniciaEscola();
                    escola = end.getEscola();
                    nomeAlunoCmeiEscolaOutro = escola.getNomeEscola();
                    break;
                    
                case "OUTRO":
                    iniciaOutro();
                    outro = end.getOutro();
                    nomeAlunoCmeiEscolaOutro = outro.getNomeOutro();
                    break;
                
            }
            
            modelo.addRow(new String[]{nomeAlunoCmeiEscolaOutro, end.getTipoEndereco(), end.getEndereco(), end.getNumeroEndereco(), end.getBairro(), end.getCidade(), end.getUf(), String.valueOf(end.getCodigoEndereco())});

        }

        dao.encerraSessao();
        
        if (jtbBuscaEndereco.getRowCount() > 0) {
            jtbBuscaEndereco.getSelectionModel().setSelectionInterval(0, 0);
        } else {
            iniciaClasseGeral();
            
            classeGeral.msgInforma("Não há endereços cadastrados!");
            
        }

    }

    public void buscaDados() {

        iniciaEndereco();
        
        DAO dao = new DAO();

        int codigo;

        codigo = Integer.valueOf(jtbBuscaEndereco.getValueAt(jtbBuscaEndereco.getSelectedRow(), 7).toString());

        endereco = (Endereco) dao.busca(endereco, codigo);
        dao.encerraSessao();

    }

//Geradores, Validadores===========================================================================================================================================
    public void iniciaAluno() {
        
        if (aluno == null) {
            aluno = new Aluno();
        }
        
    }
    
    public void iniciaClasseGeral() {
        
        if (classeGeral == null) {
            classeGeral = new ClasseGeral();
        }
        
    }
    
    public void iniciaCmei() {
        
        if (cmei == null) {
            cmei = new Cmei();
        }
        
    }
    
    public void iniciaControleAluno() {
        
        if (controleAluno == null) {
            controleAluno = new ControleAluno();
        }
        
    }
    
    public void iniciaControleCmei() {
        
        if (controleCmei == null) {
            controleCmei = new ControleCmei();
        }
        
    }
    
    public void iniciaControleEscola() {
        
        if (controleEscola == null) {
            controleEscola = new ControleEscola();
        }
        
    }
    
    public void iniciaControleOutro() {
        
        if (controleOutro == null) {
            controleOutro = new ControleOutro();
        }
        
    }
    
    public void iniciaDao() {
        
        if (dao == null) {
            dao = new DAO();
        }
        
    }
    
    public void iniciaEscola() {
        
        if (escola == null) {
            escola = new Escola();
        }
        
    }
    
    public void iniciaTabela() {
        
        if (modelo == null) {
            modelo = (DefaultTableModel) jtbBuscaEndereco.getModel(); 
        }
        
    }
    
    public void iniciaOutro() {
        
        if (outro == null) {
            outro = new Outro();
        }
        
    }
    
    public void iniciaEndereco() {
        
        if (endereco == null) {
            endereco = new Endereco();
        }
        
    }
    
//Getters and Setters===========================================================================================================================================
    public void setNumeroCaracteres() {

        jtfBuscaEndereco.setDocument(new FixedLengthDocument(240));
        jtfBuscaCidadeEndereco.setDocument(new FixedLengthDocument(240));
        jtfBuscaNumeroEndereco.setDocument(new FixedLengthDocument(10));

    }

    public int getCodigoUsuario() {
        return codigoUsuario;
    }

    public void setCodigoUsuario(int codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
    }

    public int getCodigoAluno() {
        return codigoAluno;
    }

    public void setCodigoAluno(int codigoAluno) {
        this.codigoAluno = codigoAluno;
    }

    public int getCodigoCmei() {
        return codigoCmei;
    }

    public void setCodigoCmei(int codigoCmei) {
        this.codigoCmei = codigoCmei;
    }

    public int getCodigoEscola() {
        return codigoEscola;
    }

    public void setCodigoEscola(int codigoEscola) {
        this.codigoEscola = codigoEscola;
    }

    public int getCodigoOutro() {
        return codigoOutro;
    }

    public void setCodigoOutro(int codigoOutro) {
        this.codigoOutro = codigoOutro;
    }

    public Aluno getAluno() {
        return aluno;
    }

    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }

    public Cmei getCmei() {
        return cmei;
    }

    public void setCmei(Cmei cmei) {
        this.cmei = cmei;
    }

    public Escola getEscola() {
        return escola;
    }

    public void setEscola(Escola escola) {
        this.escola = escola;
    }

    public Outro getOutro() {
        return outro;
    }

    public void setOutro(Outro outro) {
        this.outro = outro;
    }

    public void getPermissoes() {
        Permissoes permissoes;
        DAO dao = new DAO();

        permissoes = (Permissoes) dao.buscaPermissoes(getCodigoUsuario());

    }

    public Endereco getEndereco() {
        return endereco;
    }

    public void setEndereco() {
        this.endereco = null;
        
        codigoAluno = 0;
        codigoCmei = 0;
        codigoEscola = 0;
        codigoOutro = 0;
    }

//Metodos DAO===========================================================================================================================================


}
