/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfCadastroMultimidia.java
 *
 * Created on 31/05/2010, 19:18:30
 */
package visual;

import conexao.Conexao;
import controlador.*;
import dao.DAO;
import excecoes.ExcCadastro;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Equipamento;
import modelo.Permissoes;
import modelo.TipoEquipamento;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author luizam
 */
public class JfCadastroEquipamento extends javax.swing.JFrame {

    private static ControleVersao versao = new ControleVersao();
    private ClasseGeral classeGeral;
    private ControleImagem controleImagem = new ControleImagem();
    private ControleTipoEquipamento controleTipoEquipamento;
    private DAO dao;
    private Equipamento equipamento;
    private Log geraLog;
    private TipoEquipamento tipoEquipamento;
    
    private JdBuscaEquipamentos jdbe;
    private JfCadastroTipoEquipamento jfCadTipoEquipamento;
    
    private JasperPrint jPrint;
    private JasperViewer jViewer;

    private int codigo = 0;
    private int codigoUsuario;
    private String opcao = "salvar";
    private boolean cadastrarEquipamento;
    private boolean disponibilidadeEmprestimo = true;

    /** Creates new form jfCadastroMultimidia */
    public JfCadastroEquipamento() {
        super("Cadastro Equipamento - " + versao.getVersao() + " - " + versao.getAno());
        initComponents();

        //Altera icone na barra de titulo
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage("C:/SURGI/imagens/SURGI32x32.png");
        this.setIconImage(img);

        //centraliza tela
        setSize(getWidth(), getHeight());
        setLocationRelativeTo(null);

        preencheComboTipoEquipamento();

        setNumeroCaracteres();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBotoes = new javax.swing.JPanel();
        jbSalvar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbImprimir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfMarca = new javax.swing.JTextField();
        jtfModelo = new javax.swing.JTextField();
        jtfCor = new javax.swing.JTextField();
        jtfPatrimonio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbTipoEquipamento = new javax.swing.JComboBox();
        jbNovoEquipamento = new javax.swing.JButton();
        jcboxDisponibilidadeEmprestimo = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpBotoes.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jbSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/OK.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbAlterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reload.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbAlterar.setEnabled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbImprimir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir.png"))); // NOI18N
        jbImprimir.setText("Imprimir");
        jbImprimir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbImprimir.setEnabled(false);
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesLayout = new javax.swing.GroupLayout(jpBotoes);
        jpBotoes.setLayout(jpBotoesLayout);
        jpBotoesLayout.setHorizontalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBotoesLayout.setVerticalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Marca: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Modelo: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Cor: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Patrimônio: ");

        jtfMarca.setBackground(new java.awt.Color(204, 204, 255));
        jtfMarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfMarca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfMarcaFocusLost(evt);
            }
        });

        jtfModelo.setBackground(new java.awt.Color(204, 204, 255));
        jtfModelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfModelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfModeloFocusLost(evt);
            }
        });

        jtfCor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfCor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfCor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCorFocusLost(evt);
            }
        });

        jtfPatrimonio.setBackground(new java.awt.Color(204, 204, 255));
        jtfPatrimonio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfPatrimonio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfPatrimonio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfPatrimonioFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tipo de Equipamento: ");

        jcbTipoEquipamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbTipoEquipamento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbNovoEquipamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbNovoEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo02.png"))); // NOI18N
        jbNovoEquipamento.setText("Novo Tipo de Equipamento");
        jbNovoEquipamento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbNovoEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoEquipamentoActionPerformed(evt);
            }
        });

        jcboxDisponibilidadeEmprestimo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcboxDisponibilidadeEmprestimo.setSelected(true);
        jcboxDisponibilidadeEmprestimo.setText("Sim");
        jcboxDisponibilidadeEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxDisponibilidadeEmprestimoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Disponível para Empréstimo: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcboxDisponibilidadeEmprestimo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbTipoEquipamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(jtfModelo)
                            .addComponent(jtfCor)
                            .addComponent(jtfPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbNovoEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbTipoEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNovoEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboxDisponibilidadeEmprestimo)
                    .addComponent(jLabel6))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        if (opcao.equals("salvar")) {

            salvar();
            opcao = "salvar";

        } else if (opcao.equals("alterar")) {

            atualizar();
            opcao = "salvar";

        }
}//GEN-LAST:event_jbSalvarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        if (jdbe == null) {
            jdbe = new JdBuscaEquipamentos(null, true);
        }

        jdbe.setVisible(true);

        setMultimidiaBuscado(jdbe.getEquipamento());
        jdbe.setEquipamento();
}//GEN-LAST:event_jbBuscarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        cancelar();
}//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        excluir();
}//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed

        abilitaCampos();

        jbAlterar.setEnabled(false);

        opcao = "alterar";

        jbSalvar.setEnabled(true);

}//GEN-LAST:event_jbAlterarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fechar();
    }//GEN-LAST:event_formWindowClosing

    private void jtfMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfMarcaFocusLost
        jtfMarca.setText(jtfMarca.getText().toUpperCase());
    }//GEN-LAST:event_jtfMarcaFocusLost

    private void jtfModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfModeloFocusLost
        jtfModelo.setText(jtfModelo.getText().toUpperCase());
    }//GEN-LAST:event_jtfModeloFocusLost

    private void jtfCorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCorFocusLost
        jtfCor.setText(jtfCor.getText().toUpperCase());
    }//GEN-LAST:event_jtfCorFocusLost

    private void jtfPatrimonioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPatrimonioFocusLost
        jtfPatrimonio.setText(jtfPatrimonio.getText().toUpperCase());
    }//GEN-LAST:event_jtfPatrimonioFocusLost

    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed

        //ADOGeral ag = new ADOGeral();
        Conexao conexao = new Conexao();
        HashMap parametros = new HashMap();
        try {
            //System.out.println(codigoRegistro);
            //parametros.put("titulo", "Titulo Relatorio");
            parametros.put("codigoEquipamento", new Integer(codigo));
            //parametros.put("codigo", lista.get(0).getNome();
            //ADOGeral.conectar();
            conexao.getConexao();
        } catch (ExcCadastro ex) {
            Logger.getLogger(JfImpressosAgendamento.class.getName()).log(Level.SEVERE, null, ex);
        }

        //        JRDataSource jrds = new JRBeanCollectionDataSource(lista);

        try {

            //jReport = JasperCompileManager.compileReport("E:/LUIZ/PROJETOS JAVA/CORPORATIVO/m2GestaoClinicas/FichaPaciente.jrxml");
            //jPrint = JasperFillManager.fillReport("C:/m2GestaoClinicas/FichaPaciente.jasper", parametros, ADOGeral.getConexao());
            jPrint = JasperFillManager.fillReport("Equipamento.jasper", parametros, conexao.getConexao());
            //jPrint = JasperFillManager.fillReport(jReport, parametros, jrds);

            //if (!(jViewer == null)) {
            //jViewer = new JasperViewer(jPrint, false);
            //jViewer.setExtendedState(JFrame.MAXIMIZED_BOTH);
            jViewer.viewReport(jPrint, false);
            //}

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jbImprimirActionPerformed

    private void jbNovoEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoEquipamentoActionPerformed

        if (jfCadTipoEquipamento == null) {
            jfCadTipoEquipamento = new JfCadastroTipoEquipamento();
        }

        jfCadTipoEquipamento.setCodigoUsuario(codigoUsuario);
        jfCadTipoEquipamento.setVisible(true);
        preencheComboTipoEquipamento();

}//GEN-LAST:event_jbNovoEquipamentoActionPerformed

    private void jcboxDisponibilidadeEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxDisponibilidadeEmprestimoActionPerformed
        if (jcboxDisponibilidadeEmprestimo.isSelected()) {
            disponibilidadeEmprestimo = true;
        } else {
            disponibilidadeEmprestimo = false;
        }
    }//GEN-LAST:event_jcboxDisponibilidadeEmprestimoActionPerformed
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new jfCadastroMultimidia().setVisible(true);
    }
    });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JButton jbNovoEquipamento;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox jcbTipoEquipamento;
    private javax.swing.JCheckBox jcboxDisponibilidadeEmprestimo;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JTextField jtfCor;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfModelo;
    private javax.swing.JTextField jtfPatrimonio;
    // End of variables declaration//GEN-END:variables

//Outros Metodos ===========================================================================================================================================
    public void fechar() {

        if (!jtfMarca.getText().isEmpty() || !jtfModelo.getText().isEmpty() || !jtfCor.getText().isEmpty() || !jtfPatrimonio.getText().isEmpty()) {
            iniciaClasseGeral();
            classeGeral.msgAtencao("Cancele ou Salve o Cadastro em Edição!");
        } else {
            dao = null;
            this.dispose();
        }

    }

    public void cancelar() {

        jtfMarca.setText("");
        jtfModelo.setText("");
        jtfCor.setText("");
        jtfPatrimonio.setText("");
        jcbTipoEquipamento.setSelectedIndex(0);
        jcboxDisponibilidadeEmprestimo.setSelected(true);

        abilitaCampos();

        desabilitaBotoes();

        jtfModelo.transferFocusBackward();

        equipamento = null;
        tipoEquipamento = null;
        opcao = "salvar";

        preencheComboTipoEquipamento();

    }

    public void abilitaCampos() {

        jtfMarca.setEditable(true);
        jtfPatrimonio.setEditable(true);
        jtfModelo.setEditable(true);
        jtfCor.setEditable(true);
        jcbTipoEquipamento.setEnabled(true);
        jcboxDisponibilidadeEmprestimo.setEnabled(true);

    }

    public void desabilitaCampos() {

        jtfMarca.setEditable(false);
        jtfModelo.setEditable(false);
        jtfCor.setEditable(false);
        jtfPatrimonio.setEditable(false);
        jcbTipoEquipamento.setEnabled(false);
        jcboxDisponibilidadeEmprestimo.setEnabled(false);

    }

    public void abilitaBotoes() {

        jbCancelar.setEnabled(true);
        jbBuscar.setEnabled(true);
        jbImprimir.setEnabled(true);

        if (cadastrarEquipamento == true) {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(true);
            jbAlterar.setEnabled(true);
        } else {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        }

    }

    public void desabilitaBotoes() {

        jbCancelar.setEnabled(true);
        jbBuscar.setEnabled(true);
        jbImprimir.setEnabled(false);

        if (cadastrarEquipamento == true) {
            jbSalvar.setEnabled(true);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        } else {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        }

    }

     public void preencheComboTipoEquipamento() {

        iniciaDao();

        List listaTipoEquipamentos = new ArrayList();

        jcbTipoEquipamento.removeAllItems();

        listaTipoEquipamentos = dao.listarTipoEquipamentos(0, "");

        for (int i = 0; i < listaTipoEquipamentos.size(); i++) {
            iniciaTipoEquipamento();
            tipoEquipamento = (TipoEquipamento) listaTipoEquipamentos.get(i);
            jcbTipoEquipamento.addItem(tipoEquipamento.getNomeTipoEquipamento());
        }

        jcbTipoEquipamento.setSelectedIndex(0);

    }

//Geradores, Validadores===========================================================================================================================================
    public void iniciaClasseGeral() {
        
        if (classeGeral == null) {
            classeGeral = new ClasseGeral();
        }
        
    }
    
    public void iniciaControleTipoEquipamento() {
        
        if (controleTipoEquipamento == null) {
            controleTipoEquipamento = new ControleTipoEquipamento();
        }
        
    }
     
    public void iniciaDao() {

        if (dao == null) {
            dao = new DAO();
        }

    }
    
    public void iniciaEquipamento() {
        
        if (equipamento == null) {
            equipamento = new Equipamento();
        }
        
    }
    
    public void iniciaLog() {
        
        if (geraLog == null) {
            geraLog = new Log();
        }
        
    }
    
    public void iniciaTipoEquipamento() {
        
        if (tipoEquipamento == null) {
            tipoEquipamento = new TipoEquipamento();
        }
        
    }
     
//Getters and Setters===========================================================================================================================================
    public void setMultimidiaBuscado(Equipamento equipamentoBuscado) {

        if (equipamentoBuscado == null) {
        } else {

            iniciaEquipamento();
            iniciaTipoEquipamento();
            
            int codigoAux;

            jtfMarca.setText(equipamentoBuscado.getMarcaEquipamento());
            jtfModelo.setText(equipamentoBuscado.getModeloEquipamento());
            jtfCor.setText(equipamentoBuscado.getCorEquipamento());
            jtfPatrimonio.setText(equipamentoBuscado.getPatrimonioEquipamento());
            
            tipoEquipamento = equipamentoBuscado.getTipoEquipamento();
            jcbTipoEquipamento.setSelectedItem(tipoEquipamento.getNomeTipoEquipamento());
            
            jcboxDisponibilidadeEmprestimo.setSelected(equipamentoBuscado.isDiponibilidadeEmprestimo());

            codigoAux = equipamentoBuscado.getCodigoEquipamento();
            codigo = equipamentoBuscado.getCodigoEquipamento();
            equipamento.setCodigoEquipamento(codigoAux);

            desabilitaCampos();

            abilitaBotoes();

        }

    }

    public void setNumeroCaracteres() {

        jtfMarca.setDocument(new FixedLengthDocument(120));
        jtfModelo.setDocument(new FixedLengthDocument(120));
        jtfCor.setDocument(new FixedLengthDocument(60));
        jtfPatrimonio.setDocument(new FixedLengthDocument(10));

    }

    public int getCodigoUsuario() {
        return codigoUsuario;
    }

    public void setCodigoUsuario(int codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
        getPermissoes();
        desabilitaBotoes();
    }

    public void getPermissoes() {
        Permissoes permissoes;
        iniciaDao();
        //DAO dao = new DAO();

        permissoes = (Permissoes) dao.buscaPermissoes(getCodigoUsuario());

        cadastrarEquipamento = permissoes.isCadastrarEquipamento();
    }

//Metodos DAO===========================================================================================================================================
    public void salvar() {

        if (!jtfMarca.getText().isEmpty() && !jtfModelo.getText().isEmpty() && !jtfPatrimonio.getText().isEmpty()) {

            iniciaDao();
            iniciaControleTipoEquipamento();
            iniciaEquipamento();
            iniciaTipoEquipamento();

            equipamento.setMarcaEquipamento(jtfMarca.getText());
            equipamento.setModeloEquipamento(jtfModelo.getText());
            equipamento.setCorEquipamento(jtfCor.getText());
            equipamento.setDiponibilidadeEmprestimo(disponibilidadeEmprestimo);
            equipamento.setPatrimonioEquipamento(jtfPatrimonio.getText());
            
            tipoEquipamento = (TipoEquipamento) dao.busca(tipoEquipamento, controleTipoEquipamento.getCodigoEquipamento(jcbTipoEquipamento.getSelectedItem().toString()));
            dao.encerraSessao();
            equipamento.setTipoEquipamento(tipoEquipamento);

            try {
                iniciaLog();
                geraLog.criaLog(codigoUsuario, "Cadastro Equipamento", "Tentou Salvar " + equipamento.getTipoEquipamento() + " Marca " + equipamento.getMarcaEquipamento() + " Modelo " + equipamento.getModeloEquipamento() + " Patrimônio " + equipamento.getPatrimonioEquipamento());
            } catch (IOException ex) {
                Logger.getLogger(JfPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            dao.inserir(equipamento, 7, codigoUsuario);
            cancelar();

        } else {
            iniciaClasseGeral();
            classeGeral.msgAtencao("Complete os Campos Obrigatórios, destacados em Azul!");
        }

    }

    public void atualizar() {

        if (!jtfMarca.getText().isEmpty() && !jtfModelo.getText().isEmpty() && !jtfPatrimonio.getText().isEmpty()) {

            iniciaDao();
            iniciaControleTipoEquipamento();
            iniciaEquipamento();
            iniciaTipoEquipamento();

            equipamento.setMarcaEquipamento(jtfMarca.getText());
            equipamento.setModeloEquipamento(jtfModelo.getText());
            equipamento.setCorEquipamento(jtfCor.getText());
            equipamento.setDiponibilidadeEmprestimo(disponibilidadeEmprestimo);
            equipamento.setPatrimonioEquipamento(jtfPatrimonio.getText());
            
            tipoEquipamento = (TipoEquipamento) dao.busca(tipoEquipamento, controleTipoEquipamento.getCodigoEquipamento(jcbTipoEquipamento.getSelectedItem().toString()));
            dao.encerraSessao();
            equipamento.setTipoEquipamento(tipoEquipamento);

            try {
                iniciaLog();
                geraLog.criaLog(codigoUsuario, "Cadastro Equipamento", "Tentou Atualizar Código: " + equipamento.getCodigoEquipamento() + " " + equipamento.getTipoEquipamento() + " Marca " + equipamento.getMarcaEquipamento() + " Modelo " + equipamento.getModeloEquipamento() + " Patrimônio " + equipamento.getPatrimonioEquipamento());
            } catch (IOException ex) {
                Logger.getLogger(JfPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            dao.atualizar(equipamento, 7, codigoUsuario);
            cancelar();

        } else {
            iniciaClasseGeral();
            classeGeral.msgAtencao("Complete os Campos Obrigatórios, destacados em Azul!");
        }

    }

    public void excluir() {

        iniciaClasseGeral();

        if (classeGeral.msgConfirma("Deseja excluir o Equipamento ?")) {

            iniciaEquipamento();
            iniciaDao();
            
            try {
                iniciaLog();
                geraLog.criaLog(codigoUsuario, "Cadastro Equipamento", "Tentou Excluir Código: " + equipamento.getCodigoEquipamento() + " " + equipamento.getTipoEquipamento() + " Marca " + equipamento.getMarcaEquipamento() + " Modelo " + equipamento.getModeloEquipamento() + " Patrimônio " + equipamento.getPatrimonioEquipamento());
            } catch (IOException ex) {
                Logger.getLogger(JfPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            dao.excluir(equipamento, codigoUsuario);
            cancelar();

        }

    }
}
