/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfCadastroUsuario.java
 *
 * Created on 27/01/2010, 09:03:06
 */
package visual;

import controlador.*;
import dao.DAO;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Cartucho;
import modelo.Cmei;
import modelo.Escola;
import modelo.ModeloCartucho;
import modelo.Outro;
import modelo.Permissoes;

/**
 *
 * @author luiz
 */
public class JfCadastroCartucho extends javax.swing.JFrame {

    private static ControleVersao versao = new ControleVersao();
    private Cartucho cartucho;
    private Cmei cmei;
    private ControleCmei controleCmei;
    private ControleEscola controleEscola;
    private ControleImagem controleImagem = new ControleImagem();
    private ControleModeloCartucho controleModeloCartucho;
    private ControleOutro controleOutro;
    private ClasseGeral classeGeral;
    private DAO dao;
    private EnviaEmail enviaEmail;
    private Escola escola;
    private Log geraLog;
    private ModeloCartucho modeloCartucho;
    private Outro outro;
    private ValidaData validaData;
    
    private JdBuscaCartucho jdbc;
    
    private int codigo = 0;
    private int codigoUsuario;
    private String tipoEntid = "";
    private String opcao = "salvar";
    private String codigoBarrasVerificado;
    private boolean cadastrarCartucho;
    private boolean cartuchoQueimado = false;

    /** Creates new form jfCadastroUsuario */
    public JfCadastroCartucho() {
        super("Cadastro Cartuchos - " + versao.getVersao() + " - " + versao.getAno());
        initComponents();

        //Altera icone na barra de titulo
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage("C:/SURGI/imagens/SURGI32x32.png");
        this.setIconImage(img);

        //centraliza tela
        setSize(getWidth(), getHeight());
        setLocationRelativeTo(null);

        setNumeroCaracteres();

        jrbEscola.setSelected(true);

        preencheComboEscolas();
        preencheComboModeloCartucho();

        jrbOutros.transferFocus();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgEntidadesCadastroCartucho = new javax.swing.ButtonGroup();
        jpBotoes = new javax.swing.JPanel();
        jbSalvar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbImprimir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jrbEscola = new javax.swing.JRadioButton();
        jrbCmei = new javax.swing.JRadioButton();
        jrbOutros = new javax.swing.JRadioButton();
        jtfCodigoBarras = new javax.swing.JTextField();
        jcbNomeEntidade = new javax.swing.JComboBox();
        jcheckbCartuchoQueimado = new javax.swing.JCheckBox();
        jcbModeloCartucho = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpBotoes.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jbSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/OK.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbAlterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reload.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbAlterar.setEnabled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbImprimir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir.png"))); // NOI18N
        jbImprimir.setText("Imprimir");
        jbImprimir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbImprimir.setEnabled(false);
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesLayout = new javax.swing.GroupLayout(jpBotoes);
        jpBotoes.setLayout(jpBotoesLayout);
        jpBotoesLayout.setHorizontalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotoesLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpBotoesLayout.setVerticalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Código de Barras: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Modelo Cartucho: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tipo Entidade: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Unidade: ");

        btgEntidadesCadastroCartucho.add(jrbEscola);
        jrbEscola.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbEscola.setSelected(true);
        jrbEscola.setText("Escola");
        jrbEscola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEscolaActionPerformed(evt);
            }
        });

        btgEntidadesCadastroCartucho.add(jrbCmei);
        jrbCmei.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbCmei.setText("Cmei");
        jrbCmei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCmeiActionPerformed(evt);
            }
        });

        btgEntidadesCadastroCartucho.add(jrbOutros);
        jrbOutros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbOutros.setText("Outros");
        jrbOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOutrosActionPerformed(evt);
            }
        });

        jtfCodigoBarras.setBackground(new java.awt.Color(204, 204, 255));
        jtfCodigoBarras.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfCodigoBarras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfCodigoBarras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoBarrasFocusLost(evt);
            }
        });

        jcbNomeEntidade.setBackground(new java.awt.Color(204, 204, 255));
        jcbNomeEntidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbNomeEntidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), null, new java.awt.Color(204, 204, 255)));

        jcheckbCartuchoQueimado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcheckbCartuchoQueimado.setText("Cartucho Queimado");
        jcheckbCartuchoQueimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckbCartuchoQueimadoActionPerformed(evt);
            }
        });

        jcbModeloCartucho.setBackground(new java.awt.Color(204, 204, 255));
        jcbModeloCartucho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbModeloCartucho.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), null, new java.awt.Color(204, 204, 255)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Legenda para Modelos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("BRO = BROTHER");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("HP = HP");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("KYO = KYOCERA");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("LEX = LEXMARK");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("SAM = SAMSUNG");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("TOS = TOSHIBA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbEscola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbCmei)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbOutros)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfCodigoBarras, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbNomeEntidade, javax.swing.GroupLayout.Alignment.LEADING, 0, 345, Short.MAX_VALUE)
                            .addComponent(jcheckbCartuchoQueimado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbModeloCartucho, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jrbEscola)
                            .addComponent(jrbCmei)
                            .addComponent(jrbOutros))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcbModeloCartucho, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcbNomeEntidade, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcheckbCartuchoQueimado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        verificaCodigoBarras();

        if (opcao.equals("salvar")) {

            if (!codigoBarrasVerificado.isEmpty()) {
                iniciaClasseGeral();
                classeGeral.msgAtencao("Este Código de Barras já está cadastrado!");
            } else {
                salvar();
                opcao = "salvar";
            }

        } else if (opcao.equals("alterar")) {

            atualizar();
            opcao = "salvar";

        }

    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        if (jdbc == null) {
            jdbc = new JdBuscaCartucho(null, true);
        }

        jdbc.setVisible(true);

        setCartuchoBuscado(jdbc.getCartucho());
        jdbc.setCartucho();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        cancelar();
}//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        excluir();
}//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed

        abilitaCampos();

        jbAlterar.setEnabled(false);

        opcao = "alterar";

        jbSalvar.setEnabled(true);

    }//GEN-LAST:event_jbAlterarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fechar();
    }//GEN-LAST:event_formWindowClosing

    private void jrbEscolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEscolaActionPerformed

        if (jrbEscola.isSelected()) {
            preencheComboEscolas();
            tipoEntid = "ESCOLA";
        }

    }//GEN-LAST:event_jrbEscolaActionPerformed

    private void jrbCmeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCmeiActionPerformed

        if (jrbCmei.isSelected()) {
            preencheComboCmeis();
            tipoEntid = "CMEI";
        }

    }//GEN-LAST:event_jrbCmeiActionPerformed

    private void jrbOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOutrosActionPerformed

        if (jrbOutros.isSelected()) {
            preencheComboOutros();
            tipoEntid = "OUTROS";
        }

    }//GEN-LAST:event_jrbOutrosActionPerformed

    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed

        iniciaClasseGeral();
        classeGeral.msgAtencao("Atenção, Opção de Impressão ainda não disponivel!");

    }//GEN-LAST:event_jbImprimirActionPerformed

    private void jtfCodigoBarrasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoBarrasFocusLost

        if (!jtfCodigoBarras.getText().isEmpty()) {
            
            iniciaClasseGeral();
        
            jtfCodigoBarras.setText(classeGeral.somenteNumero(jtfCodigoBarras.getText()));
        
        }

    }//GEN-LAST:event_jtfCodigoBarrasFocusLost

    private void jcheckbCartuchoQueimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckbCartuchoQueimadoActionPerformed
        if (jcheckbCartuchoQueimado.isSelected()) {

            cartuchoQueimado = true;

        } else {

            cartuchoQueimado = false;

        }
    }//GEN-LAST:event_jcheckbCartuchoQueimadoActionPerformed
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new jfCadastroUsuario().setVisible(true);
    }
    });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgEntidadesCadastroCartucho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox jcbModeloCartucho;
    private javax.swing.JComboBox jcbNomeEntidade;
    private javax.swing.JCheckBox jcheckbCartuchoQueimado;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JRadioButton jrbCmei;
    private javax.swing.JRadioButton jrbEscola;
    private javax.swing.JRadioButton jrbOutros;
    private javax.swing.JTextField jtfCodigoBarras;
    // End of variables declaration//GEN-END:variables

//Outros Metodos===================================================================================================================================
    public void fechar() {

        if (!jtfCodigoBarras.getText().isEmpty() || jcbModeloCartucho.getSelectedIndex() != 0 || jcbNomeEntidade.getSelectedIndex() != 0) {

            iniciaClasseGeral();
            classeGeral.msgAtencao("Cancele ou Salve o Cadastro em Edição!");

        } else {

            dao = null;
            this.dispose();

        }
    }

    public void cancelar() {

        jrbEscola.setSelected(true);
        jtfCodigoBarras.setText("");
        jcbModeloCartucho.setSelectedIndex(0);
        jcbNomeEntidade.setSelectedIndex(0);
        jcheckbCartuchoQueimado.setSelected(false);

        preencheComboEscolas();

        abilitaCampos();

        desabilitaBotoes();

        opcao = "salvar";

        jrbOutros.transferFocus();

        cartucho = null;
        cartuchoQueimado = false;
        cmei = null;
        escola = null;
        modeloCartucho = null;
        outro = null;

    }

    public void abilitaCampos() {

        jrbEscola.setEnabled(true);
        jrbCmei.setEnabled(true);
        jrbOutros.setEnabled(true);
        jtfCodigoBarras.setEditable(true);
        jcbModeloCartucho.setEnabled(true);
        jcbNomeEntidade.setEnabled(true);
        jcheckbCartuchoQueimado.setEnabled(true);

    }

    public void desabilitaCampos() {

        jrbEscola.setEnabled(false);
        jrbCmei.setEnabled(false);
        jrbOutros.setEnabled(false);
        jtfCodigoBarras.setEditable(false);
        jcbModeloCartucho.setEnabled(false);
        jcbNomeEntidade.setEnabled(false);
        jcheckbCartuchoQueimado.setEnabled(false);

    }

    public void abilitaBotoes() {

        jbCancelar.setEnabled(true);
        jbBuscar.setEnabled(true);
        jbImprimir.setEnabled(true);

        if (cadastrarCartucho == true) {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(true);
            jbAlterar.setEnabled(true);
        } else {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        }

    }

    public void desabilitaBotoes() {

        jbCancelar.setEnabled(true);
        jbBuscar.setEnabled(true);
        jbImprimir.setEnabled(false);

        if (cadastrarCartucho == true) {
            jbSalvar.setEnabled(true);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        } else {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        }

    }

    public void preencheComboEscolas() {

        iniciaDao();
        
        List listaEscolas = new ArrayList();

        jcbNomeEntidade.removeAllItems();
        jcbNomeEntidade.addItem("");

        listaEscolas = dao.listarEscolas(0, "", "");

        for (int i = 0; i < listaEscolas.size(); i++) {
            iniciaEscola();
            escola = (Escola) listaEscolas.get(i);
            jcbNomeEntidade.addItem(escola.getNomeEscola());
        }

    }

    public void preencheComboCmeis() {

        iniciaDao();
        
        List listaCmeis = new ArrayList();

        jcbNomeEntidade.removeAllItems();
        jcbNomeEntidade.addItem("");

        listaCmeis = dao.listarCmeis(0, "", "");

        for (int i = 0; i < listaCmeis.size(); i++) {
            iniciaCmei();
            cmei = (Cmei) listaCmeis.get(i);
            jcbNomeEntidade.addItem(cmei.getNomeCmei());
        }
    }

    public void preencheComboOutros() {

        iniciaDao();
        
        List listaOutros = new ArrayList();

        jcbNomeEntidade.removeAllItems();
        jcbNomeEntidade.addItem("");

        listaOutros = dao.listarOutros(0, "", "");

        for (int i = 0; i < listaOutros.size(); i++) {
            iniciaOutro();
            outro = (Outro) listaOutros.get(i);
            jcbNomeEntidade.addItem(outro.getNomeOutro());
        }

    }
    
    public void preencheComboModeloCartucho() {
        
        iniciaDao();
        
        List listaModelosCartuchos = new ArrayList();
        
        jcbModeloCartucho.removeAllItems();
        jcbModeloCartucho.addItem("");
        
        listaModelosCartuchos = dao.listarModelosCartuchos("", "");

        for (int i = 0; i < listaModelosCartuchos.size(); i++) {
            iniciaModeloCartucho();
            modeloCartucho = (ModeloCartucho) listaModelosCartuchos.get(i);
            jcbModeloCartucho.addItem(modeloCartucho.getNomeModeloCartucho());
        }
        
    }

//Geradores, Validadores, Verificadores===================================================================================================================================
    public void iniciaCartucho() {
        
        if (cartucho == null) {
            cartucho = new Cartucho();
        }
        
    }
    
    public void iniciaClasseGeral() {
        
        if (classeGeral == null) {
            classeGeral = new ClasseGeral();
        }
        
    }
    
    public void iniciaCmei() {
        
        if (cmei == null) {
            cmei = new Cmei();
        }
        
    }
    
    public void iniciaControleCmei(){
        
        if (controleCmei == null) {
            controleCmei = new ControleCmei();
        }
        
    }
    
    public void iniciaControleEscola() {
        
        if (controleEscola == null) {
            controleEscola = new ControleEscola();
        }
        
    }
    
    public void iniciaControleModeloCartucho() {
        
        if (controleModeloCartucho == null) {
            controleModeloCartucho = new ControleModeloCartucho();
        }
        
    }
    
    public void iniciaControleOutro() {
        
        if (controleOutro == null) {
            controleOutro = new ControleOutro();
        }
        
    }
    
    public void iniciaDao() {

        if (dao == null) {
            dao = new DAO();
        }

    }
    
    public void iniciaEnviaEmail() {
        
        if (enviaEmail == null) {
            enviaEmail = new EnviaEmail();
        }
        
    }
    
    public void iniciaEscola() {
        
        if (escola == null) {
            escola = new Escola();
        }
        
    }
    
    public void iniciaLog() {
        
        if (geraLog == null) {
            geraLog = new Log();
        }
        
    }
    
    public void iniciaModeloCartucho() {
        
        if (modeloCartucho == null) {
            modeloCartucho = new ModeloCartucho();
        }
        
    }
    
    public void iniciaOutro() {
        
        if (outro == null) {
            outro = new Outro();
        }
        
    }
    
    public void iniciaValidaData() {
        
        if (validaData == null) {
            validaData = new ValidaData();
        }
        
    }
    
    public void verificaCodigoBarras() {

        iniciaDao();

        codigoBarrasVerificado = dao.verificarCodigoBarras(jtfCodigoBarras.getText());

    }
    
//Getters and Setters===================================================================================================================================
    public void setCartuchoBuscado(Cartucho cartuchoBuscado) {

        if (cartuchoBuscado == null) {
        } else {

            iniciaCartucho();
            iniciaModeloCartucho();
            
            if (cartuchoBuscado.getTipoEntidade().equals("ESCOLA")) {
                
                iniciaEscola();
                jrbEscola.setSelected(true);
                preencheComboEscolas();
                
                escola = (Escola) cartuchoBuscado.getEscola();
                jcbNomeEntidade.setSelectedItem(escola.getNomeEscola());
                
            } else if (cartuchoBuscado.getTipoEntidade().equals("CMEI")) {
                
                iniciaCmei();
                jrbCmei.setSelected(true);
                preencheComboCmeis();
                
                cmei = (Cmei) cartuchoBuscado.getCmei();
                jcbNomeEntidade.setSelectedItem(cmei.getNomeCmei());
                
            } else if (cartuchoBuscado.getTipoEntidade().equals("OUTROS")) {
                
                iniciaOutro();
                jrbOutros.setSelected(true);
                preencheComboOutros();
                
                outro = (Outro) cartuchoBuscado.getOutro();
                jcbNomeEntidade.setSelectedItem(outro.getNomeOutro());
                
            }

            jtfCodigoBarras.setText(cartuchoBuscado.getCodigoBarra());
            
            modeloCartucho = cartuchoBuscado.getModeloCartucho();
            jcbModeloCartucho.setSelectedItem(modeloCartucho.getNomeModeloCartucho());
            
            jcheckbCartuchoQueimado.setSelected(cartuchoBuscado.isCartuchoQueimado());

            codigo = cartuchoBuscado.getCodigoCartucho();
            cartucho = cartuchoBuscado;
            cartucho.setCodigoCartucho(codigo);

            desabilitaCampos();

            abilitaBotoes();

        }

        jcbModeloCartucho.transferFocusBackward();

    }

    public void setNumeroCaracteres() {

        jtfCodigoBarras.setDocument(new FixedLengthDocument(80));

    }

    public int getCodigoUsuario() {
        return codigoUsuario;
    }

    public void setCodigoUsuario(int codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
        getPermissoes();
        desabilitaBotoes();
    }

    public void getPermissoes() {
        Permissoes permissoes;
        iniciaDao();
        //DAO dao = new DAO();

        permissoes = (Permissoes) dao.buscaPermissoes(codigoUsuario);

        cadastrarCartucho = permissoes.isCadastrarCartucho();
    }

//Metodos DAO===================================================================================================================================
    public void salvar() {

        if (!jtfCodigoBarras.getText().isEmpty() && jcbModeloCartucho.getSelectedIndex() !=0 && jcbNomeEntidade.getSelectedIndex() != 0) {

            iniciaDao();
            iniciaCartucho();
            iniciaControleModeloCartucho();
            iniciaModeloCartucho();
            
            cartucho.setCodigoBarra(jtfCodigoBarras.getText());
            
            modeloCartucho = (ModeloCartucho) dao.busca(modeloCartucho, controleModeloCartucho.getCodigoModeloCartucho(jcbModeloCartucho.getSelectedItem().toString()));
            dao.encerraSessao();
            cartucho.setModeloCartucho(modeloCartucho);
            
            cartucho.setCartuchoQueimado(cartuchoQueimado);
            
            if (jrbEscola.isSelected() == true) {
                
                iniciaControleEscola();
                iniciaEscola();
                cartucho.setTipoEntidade("ESCOLA");
                
                escola = (Escola) dao.busca(escola, controleEscola.getCodigoEscola(jcbNomeEntidade.getSelectedItem().toString()));
                dao.encerraSessao();
                cartucho.setEscola(escola);
                
            } else if (jrbCmei.isSelected() == true) {
                
                iniciaCmei();
                iniciaControleCmei();
                cartucho.setTipoEntidade("CMEI");

                cmei = (Cmei) dao.busca(cmei, controleCmei.getCodigoCmei(jcbNomeEntidade.getSelectedItem().toString()));
                dao.encerraSessao();
                cartucho.setCmei(cmei);
                
            } else if (jrbOutros.isSelected() == true) {
                
                iniciaControleOutro();
                iniciaOutro();
                cartucho.setTipoEntidade("OUTROS");
                
                outro = (Outro) dao.busca(outro, controleOutro.getCodigoOutro(jcbNomeEntidade.getSelectedItem().toString()));
                dao.encerraSessao();
                cartucho.setOutro(outro);
                
            }

            try {
                iniciaLog();
                geraLog.criaLog(codigoUsuario, "Cadastro Cartucho", "Tentou Salvar para " + cartucho.getTipoEntidade() + " " + jcbNomeEntidade.getSelectedItem().toString() + " Modelo: " + cartucho.getModeloCartucho());
            } catch (IOException ex) {
                Logger.getLogger(JfPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            dao.inserir(cartucho, 7, codigoUsuario);
            cancelar();

        } else {
            iniciaClasseGeral();
            classeGeral.msgAtencao("Complete os Campos Obrigatórios, destacados em Azul!");
        }

    }

    public void atualizar() {

        if (!jtfCodigoBarras.getText().isEmpty() && jcbModeloCartucho.getSelectedIndex() !=0 && jcbNomeEntidade.getSelectedIndex() != 0) {

            iniciaDao();
            iniciaCartucho();
            iniciaControleModeloCartucho();
            iniciaModeloCartucho();
            
            cartucho.setCodigoBarra(jtfCodigoBarras.getText());
            
            modeloCartucho = (ModeloCartucho) dao.busca(modeloCartucho, controleModeloCartucho.getCodigoModeloCartucho(jcbModeloCartucho.getSelectedItem().toString()));
            dao.encerraSessao();
            cartucho.setModeloCartucho(modeloCartucho);
            
            if (jrbEscola.isSelected() == true) {
                
                iniciaControleEscola();
                iniciaEscola();
                cartucho.setTipoEntidade("ESCOLA");
                
                escola = (Escola) dao.busca(escola, controleEscola.getCodigoEscola(jcbNomeEntidade.getSelectedItem().toString()));
                dao.encerraSessao();
                cartucho.setEscola(escola);
                
            } else if (jrbCmei.isSelected() == true) {
                
                iniciaCmei();
                iniciaControleCmei();
                cartucho.setTipoEntidade("CMEI");

                cmei = (Cmei) dao.busca(cmei, controleCmei.getCodigoCmei(jcbNomeEntidade.getSelectedItem().toString()));
                dao.encerraSessao();
                cartucho.setCmei(cmei);
                
            } else if (jrbOutros.isSelected() == true) {
                
                iniciaControleOutro();
                iniciaOutro();
                cartucho.setTipoEntidade("OUTROS");
                
                outro = (Outro) dao.busca(outro, controleOutro.getCodigoOutro(jcbNomeEntidade.getSelectedItem().toString()));
                dao.encerraSessao();
                cartucho.setOutro(outro);
                
            }

            if (cartucho.isCartuchoQueimado() == false && cartuchoQueimado == true) {
                iniciaEnviaEmail();
                iniciaValidaData();
                enviaEmail.enviarEmailNaoDeuRecarga(cartucho.getTipoEntidade(), jcbNomeEntidade.getSelectedItem().toString(), validaData.getDateAtual(), codigoUsuario, 
                        jcbModeloCartucho.getSelectedItem().toString(), jtfCodigoBarras.getText());
            }
            
            cartucho.setCartuchoQueimado(cartuchoQueimado);
            
            try {
                iniciaLog();
                geraLog.criaLog(codigoUsuario, "Cadastro Cartucho", "Tentou Atualizar Código: " + cartucho.getCodigoCartucho() + " do(a) " + cartucho.getTipoEntidade() + " " + 
                        jcbNomeEntidade.getSelectedItem().toString() + " Modelo: " + cartucho.getModeloCartucho());
            } catch (IOException ex) {
                Logger.getLogger(JfPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            dao.atualizar(cartucho, 7, codigoUsuario);
            cancelar();

        } else {
            iniciaClasseGeral();
            classeGeral.msgAtencao("Complete os Campos Obrigatórios, destacados em Azul!");
        }

    }

    public void excluir() {
        
        if (classeGeral.msgConfirma("Deseja excluir o cartucho ?")) {

            iniciaDao();
            iniciaCartucho();
            
            try {
                iniciaLog();
                geraLog.criaLog(codigoUsuario, "Cadastro Cartucho", "Tentou Excluir Código: " + cartucho.getCodigoCartucho() + " do(a) " + cartucho.getTipoEntidade() + " " + jcbNomeEntidade.getSelectedItem().toString() + " Modelo: " + cartucho.getModeloCartucho());
            } catch (IOException ex) {
                Logger.getLogger(JfPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            dao.excluir(cartucho, codigoUsuario);
            cancelar();

        }
    }
}
