/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import controlador.ClasseGeral;
import controlador.ControleImagem;
import controlador.ControleLote;
import controlador.ControleVersao;
import controlador.FixedLengthDocument;
import dao.DAO;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import modelo.Bloco;
import modelo.Lote;
import modelo.Permissoes;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author luizam
 */
public class JfCadastroBlocoTransporte extends javax.swing.JFrame {

    private static ControleVersao versao = new ControleVersao();
    private ClasseGeral classeGeral;
    private ControleLote controleLote;
    private ControleImagem controleImagem = new ControleImagem();
    private DAO dao;
    private Bloco bloco;
    private Bloco blocoVerificado;
    private Lote lote;
    private Permissoes permissoes;

    private JdBuscaBloco jdbb;
    private JasperViewer jViewer;
    private JasperPrint jPrint;
    
    private int codigo;
    private int codigoUsuario;
    private String opcao = "salvar";
    
    private boolean cadastrarBloco;
    
    /**
     * Creates new form JfCadastroBairro
     */
    public JfCadastroBlocoTransporte() {
        super("m2 - Cadastro Bloco - Transporte Escolar - " + versao.getVersao() + " - " + versao.getAno());
        initComponents();

        //Altera icone na barra de titulo
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage("C:/SURGI/imagens/SURGI32x32.png");
        this.setIconImage(img);

        //centraliza tela
        setSize(getWidth(), getHeight());
        setLocationRelativeTo(null);
        
        preencheComboLote();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCadastroLoteFundo = new javax.swing.JPanel();
        jpBotoes = new javax.swing.JPanel();
        jbSalvar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbImprimir = new javax.swing.JButton();
        jpCadastroLote = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfTotalKm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNomeBloco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbLote = new javax.swing.JComboBox();
        jtfNumeroBloco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpBotoes.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/OK.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete02.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reload.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbAlterar.setEnabled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir.png"))); // NOI18N
        jbImprimir.setText("Imprimir");
        jbImprimir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbImprimir.setEnabled(false);
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesLayout = new javax.swing.GroupLayout(jpBotoes);
        jpBotoes.setLayout(jpBotoesLayout);
        jpBotoesLayout.setHorizontalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpBotoesLayout.setVerticalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jpCadastroLote.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nome Bloco: ");

        jtfTotalKm.setBackground(new java.awt.Color(205, 204, 255));
        jtfTotalKm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfTotalKm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfTotalKm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfTotalKmFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Número Bloco: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Total Km: ");

        jtfNomeBloco.setBackground(new java.awt.Color(205, 204, 255));
        jtfNomeBloco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfNomeBloco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfNomeBloco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNomeBlocoFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Lote: ");

        jcbLote.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbLote.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtfNumeroBloco.setBackground(new java.awt.Color(205, 204, 255));
        jtfNumeroBloco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfNumeroBloco.setToolTipText("Digite apenas números romanos!");
        jtfNumeroBloco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfNumeroBloco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNumeroBlocoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jpCadastroLoteLayout = new javax.swing.GroupLayout(jpCadastroLote);
        jpCadastroLote.setLayout(jpCadastroLoteLayout);
        jpCadastroLoteLayout.setHorizontalGroup(
            jpCadastroLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroLoteLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jpCadastroLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfNomeBloco, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addComponent(jcbLote, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfTotalKm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumeroBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jpCadastroLoteLayout.setVerticalGroup(
            jpCadastroLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroLoteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpCadastroLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbLote, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNumeroBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNomeBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfTotalKm, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpCadastroLoteFundoLayout = new javax.swing.GroupLayout(jpCadastroLoteFundo);
        jpCadastroLoteFundo.setLayout(jpCadastroLoteFundoLayout);
        jpCadastroLoteFundoLayout.setHorizontalGroup(
            jpCadastroLoteFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpCadastroLote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpCadastroLoteFundoLayout.setVerticalGroup(
            jpCadastroLoteFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastroLoteFundoLayout.createSequentialGroup()
                .addComponent(jpCadastroLote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCadastroLoteFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCadastroLoteFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        if (jtfTotalKm.getText().isEmpty() || jtfNomeBloco.getText().isEmpty() || jtfNumeroBloco.getText().isEmpty()) {

            iniciaClasseGeral();
            classeGeral.msgAtencao("Preencha os campos Obrigatórios em azul!");

        } else {

            if (opcao.equals("salvar")) {

                verificaCadastroBloco();

                if (blocoVerificado != null) {
                    iniciaClasseGeral();
                    classeGeral.msgAtencao("Esse Bloco já está Cadastrado!");
                } else {
                    salvar();
                    opcao = "salvar";
                }

            } else if (opcao.equals("alterar")) {

                atualizar();
                opcao = "salvar";

            }

        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        if (jdbb == null) {
            jdbb = new JdBuscaBloco(null, true);
        }

        jdbb.setVisible(true);

        setBlocoBuscado(jdbb.getBloco());
        jdbb.setBloco();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed

        abilitaCampos();

        jbAlterar.setEnabled(false);

        opcao = "alterar";
        
        jbSalvar.setEnabled(true);
        
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed

        //ADOGeral ag = new ADOGeral();
        /*Conexao conexao = new Conexao();
        HashMap parametros = new HashMap();
        try {
            //System.out.println(codigoRegistro);
            //parametros.put("titulo", "Titulo Relatorio");
            parametros.put("codigoBairro", new Integer(codigo));
            //parametros.put("codigo", lista.get(0).getNome();
                //ADOGeral.conectar();
                conexao.getConexao();
            } catch (ExcCadastro ex) {
                Logger.getLogger(JfCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

            //        JRDataSource jrds = new JRBeanCollectionDataSource(lista);

            try {

                //jReport = JasperCompileManager.compileReport("E:/LUIZ/PROJETOS JAVA/CORPORATIVO/m2GestaoClinicas/FichaPaciente.jrxml");
                //jPrint = JasperFillManager.fillReport("C:/m2GestaoClinicas/FichaPaciente.jasper", parametros, ADOGeral.getConexao());
                jPrint = JasperFillManager.fillReport("Funcao.jasper", parametros, conexao.getConexao());
                //jPrint = JasperFillManager.fillReport(jReport, parametros, jrds);

                //if (!(jViewer == null)) {
                    //jViewer = new JasperViewer(jPrint, false);
                    //jViewer.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    if (jPrint != null) {
                        jViewer.viewReport(jPrint, false);
                        jPrint = null;
                    }
                    //}

            } catch (Exception ex) {
                ex.printStackTrace();
            }*/
    }//GEN-LAST:event_jbImprimirActionPerformed

    private void jtfTotalKmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfTotalKmFocusLost
        if (!jtfTotalKm.getText().isEmpty()) {
            
            double valorKm;
            
            iniciaClasseGeral();
            
            jtfTotalKm.setText(classeGeral.pontoPorVirgula(classeGeral.somenteDouble(classeGeral.virgulaPorPonto(jtfTotalKm.getText()))));
            
        }
    }//GEN-LAST:event_jtfTotalKmFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fechar();
    }//GEN-LAST:event_formWindowClosing

    private void jtfNomeBlocoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNomeBlocoFocusLost
        if (!jtfNomeBloco.getText().isEmpty()) {
            
            jtfNomeBloco.setText(jtfNomeBloco.getText().toUpperCase());
            
        }
    }//GEN-LAST:event_jtfNomeBlocoFocusLost

    private void jtfNumeroBlocoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNumeroBlocoFocusLost
        if (!jtfNumeroBloco.getText().isEmpty()) {
            
            jtfNumeroBloco.setText(jtfNumeroBloco.getText().toUpperCase());
            
        }
    }//GEN-LAST:event_jtfNumeroBlocoFocusLost

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfCadastroBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfCadastroBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfCadastroBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfCadastroBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfCadastroBairro().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox jcbLote;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpCadastroLote;
    private javax.swing.JPanel jpCadastroLoteFundo;
    private javax.swing.JTextField jtfNomeBloco;
    private javax.swing.JTextField jtfNumeroBloco;
    private javax.swing.JTextField jtfTotalKm;
    // End of variables declaration//GEN-END:variables

//Outros Metodos ===========================================================================================================================================
    public void fechar() {
        if (!jtfNomeBloco.getText().isEmpty() || !jtfNumeroBloco.getText().isEmpty() || !jtfTotalKm.getText().isEmpty()) {
            iniciaClasseGeral();
            classeGeral.msgAtencao("Salve ou cancele o cadastro em edição!");
        } else {
            this.dispose();
        }
        
    }

    public void cancelar() {

        blocoVerificado = null;
        
        jtfNomeBloco.setText("");
        jtfNumeroBloco.setText("");
        jtfTotalKm.setText("");
        
        preencheComboLote();
        
        abilitaCampos();

        desabilitaBotoes();

        opcao = "salvar";
    }

    public void abilitaCampos() {

        jtfNomeBloco.setEnabled(true);
        jtfNumeroBloco.setEnabled(true);
        jtfTotalKm.setEnabled(true);
        jcbLote.setEnabled(true);

    }

    public void desabilitaCampos() {

        jtfNomeBloco.setEnabled(false);
        jtfNumeroBloco.setEnabled(false);
        jtfTotalKm.setEnabled(false);
        jcbLote.setEnabled(false);
        
    }

    public void abilitaBotoes() {

        jbCancelar.setEnabled(true);
        jbBuscar.setEnabled(true);
        jbImprimir.setEnabled(false);

        if (cadastrarBloco == true) {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(true);
            jbAlterar.setEnabled(true);
        } else {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        }

    }

    public void desabilitaBotoes() {

        jbCancelar.setEnabled(true);
        jbBuscar.setEnabled(true);
        jbImprimir.setEnabled(false);

        if (cadastrarBloco == true) {
            jbSalvar.setEnabled(true);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        } else {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        }

    }
    
    public void preencheComboLote() {
        
        iniciaDao();
        List listaLotes = new ArrayList();

        jcbLote.removeAllItems();
        jcbLote.addItem("");

        listaLotes = dao.listarLotes("", "");

        for (int i = 0; i < listaLotes.size(); i++) {
            iniciaLote();
            lote = (Lote) listaLotes.get(i);
            jcbLote.addItem("LOTE " + lote.getNumeroLote() + " - " + lote.getNomeLote());
            lote = null;
        }
     
        jcbLote.setSelectedIndex(0);
    }
    
//Geradores, Validadores===========================================================================================================================================
    public void iniciaClasseGeral() {
        
        if (classeGeral == null) {
            classeGeral = new ClasseGeral();
        }
        
    }
    
    public void iniciaControleLote() {
        
        if (controleLote == null) {
            controleLote = new ControleLote();
        }
        
    }
    
    public void iniciaDao() {
        
        if (dao == null) {
            dao = new DAO();
        }
        
    }
    
    public void iniciaBloco() {
        
        if (bloco == null) {
            bloco = new Bloco();
        }
        
    }
    
    public void iniciaLote() {
        
        if (lote == null) {
            lote = new Lote();
        }
        
    }
    
    public void iniciaPermissoes() {
        
        if (permissoes == null) {
            permissoes = new Permissoes();
        }
        
    }
    
    public void verificaCadastroBloco() {

        iniciaDao();
        
        blocoVerificado = (Bloco) dao.verificarCadastroBloco(jtfNomeBloco.getText());

    }
    
//Getters and Setters===========================================================================================================================================
    public void setNumeroCaracteres() {

        jtfNomeBloco.setDocument(new FixedLengthDocument(240));

    }

    public int getCodigoUsuario() {
        return codigoUsuario;
    }

    public void setCodigoUsuario(int codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
        getPermissoes();
        desabilitaBotoes();
    }

    public void getPermissoes() {
        
        iniciaDao();
        iniciaPermissoes();
        
        permissoes = (Permissoes) dao.buscaPermissoes(getCodigoUsuario());

        cadastrarBloco = permissoes.isCadastrarBloco();
    }

    public void setBlocoBuscado(Bloco blocoBuscado) {
        
        if (blocoBuscado == null) {
            
        } else {
            
            iniciaClasseGeral();
            iniciaBloco();
            
            jcbLote.setSelectedItem("LOTE " + blocoBuscado.getLote().getNumeroLote() + " - " + blocoBuscado.getLote().getNomeLote());
            jtfNomeBloco.setText(blocoBuscado.getNomeBloco());
            jtfNumeroBloco.setText(blocoBuscado.getNumeroBloco());
            jtfTotalKm.setText(classeGeral.pontoPorVirgula(String.valueOf(blocoBuscado.getTotalKm())));
            
            codigo = blocoBuscado.getCodigoBloco();
            bloco = blocoBuscado;
            bloco.setCodigoBloco(codigo);
            
            desabilitaCampos();

            opcao = "alterar";

            abilitaBotoes();
            
        }
        
    }


//Metodos DAO===========================================================================================================================================
    public void salvar() {

        iniciaDao();
        iniciaBloco();
        iniciaClasseGeral();
        iniciaControleLote();
        iniciaLote();
        
        lote = (Lote) dao.busca(lote, controleLote.getCodigoLote(controleLote.getNomeLote(jcbLote.getSelectedItem().toString())));
        bloco.setLote(lote);
        bloco.setNomeBloco(jtfNomeBloco.getText());
        bloco.setNumeroBloco(jtfNumeroBloco.getText());
        bloco.setTotalKm(Double.parseDouble(classeGeral.virgulaPorPonto(jtfTotalKm.getText())));

        dao.inserir(bloco, 7, codigoUsuario);
        cancelar();

    }
    
    public void atualizar() {

        iniciaDao();
        iniciaBloco();
        iniciaClasseGeral();
        iniciaControleLote();
        iniciaLote();

        lote = (Lote) dao.busca(lote, controleLote.getCodigoLote(controleLote.getNomeLote(jcbLote.getSelectedItem().toString())));
        bloco.setLote(lote);
        bloco.setNomeBloco(jtfNomeBloco.getText());
        bloco.setNumeroBloco(jtfNumeroBloco.getText());
        bloco.setTotalKm(Double.parseDouble(classeGeral.virgulaPorPonto(jtfTotalKm.getText())));
        
        dao.atualizar(bloco, 7, codigoUsuario);
        cancelar();

    }

    public void excluir() {

        iniciaClasseGeral();

        if (classeGeral.msgConfirma("Deseja excluir o Bloco?")) {

            iniciaDao();
            iniciaBloco();
            
            dao.excluir(bloco, codigoUsuario);
            cancelar();

        }

    }

}
