/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import controlador.*;
import dao.DAO;
import excecoes.MensagensExcessao;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Edital;
import modelo.Permissoes;
import modelo.Usuario;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author luizam
 */
public class JfEdital extends javax.swing.JFrame implements Runnable{

    private static ControleVersao versao = new ControleVersao();
    private ClasseGeral classeGeral;
    private ControleUsuario controleUsuario;
    private DAO dao;
    private Edital edital;
    private Log geraLog;
    private MensagensExcessao except;
    private Usuario usuario;

    private Thread threadAtualizaNumeroEdital = new Thread(this);
    
    private JasperPrint jPrint;
    private JasperViewer jViewer;
    private JdBuscaEdital jdbe;

    private final String TIPOEDITAL = "GERAL";
    private int codigo = 0;
    private int codigoUsuario;
    private String modeloEdital = "EDITAL";
    private String opcao = "salvar";
    private String editalVerificado;
    private boolean gerarNumeracao;
    
    /**
     * Creates new form jfEdital
     */
    public JfEdital() {
        super("Edital - " + versao.getVersao() + " - " + versao.getAno());
        initComponents();

        //Altera icone na barra de titulo
        Toolkit kit = Toolkit.getDefaultToolkit();
        java.awt.Image img = kit.getImage("C:/SURGI/imagens/SURGI32x32.png");
        this.setIconImage(img);

        //maximiza tela
        //this.setExtendedState(MAXIMIZED_BOTH);

        //centraliza tela
        setSize(getWidth(), getHeight());
        setLocationRelativeTo(null);

        jlbAnoEdital.setText(getAno());
        jDateChooserSolicitacao.setDate(getDateHoje());
        jrbEdital.setSelected(true);

        threadAtualizaNumeroEdital.start();

        preencheNumeroEdital();
        bloqueiaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbAnoEdital = new javax.swing.JLabel();
        jrbEdital = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jDateChooserSolicitacao = new com.toedter.calendar.JDateChooser();
        jtfNumeroEdital = new javax.swing.JTextField();
        jtfAssuntoEdital = new javax.swing.JTextField();
        jtfDestinatarioEdital = new javax.swing.JTextField();
        jtfDepartamentoDestinatarioEdital = new javax.swing.JTextField();
        jpBotoes = new javax.swing.JPanel();
        jbSalvar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jlbAnoEdital.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbAnoEdital.setText("Ano Edital");

        jrbEdital.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbEdital.setText("Edital");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Usuário: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Data Solicitação: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Número: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Assunto: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Destinatário: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Departamento Destinatário: ");

        jtfUsuario.setBackground(new java.awt.Color(204, 204, 255));
        jtfUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jDateChooserSolicitacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfNumeroEdital.setBackground(new java.awt.Color(204, 204, 255));
        jtfNumeroEdital.setText("1");
        jtfNumeroEdital.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfAssuntoEdital.setBackground(new java.awt.Color(204, 204, 255));
        jtfAssuntoEdital.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfAssuntoEdital.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfAssuntoEditalFocusLost(evt);
            }
        });

        jtfDestinatarioEdital.setBackground(new java.awt.Color(204, 204, 255));
        jtfDestinatarioEdital.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfDestinatarioEdital.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDestinatarioEditalFocusLost(evt);
            }
        });

        jtfDepartamentoDestinatarioEdital.setBackground(new java.awt.Color(204, 204, 255));
        jtfDepartamentoDestinatarioEdital.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfDepartamentoDestinatarioEdital.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDepartamentoDestinatarioEditalFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbAnoEdital))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jrbEdital))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfNumeroEdital, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfAssuntoEdital)
                            .addComponent(jtfDestinatarioEdital)
                            .addComponent(jtfDepartamentoDestinatarioEdital))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbAnoEdital)
                .addGap(18, 18, 18)
                .addComponent(jrbEdital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfNumeroEdital, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtfAssuntoEdital, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtfDestinatarioEdital, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfDepartamentoDestinatarioEdital, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(303, Short.MAX_VALUE))
        );

        jpBotoes.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jbSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/OK.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbAlterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reload.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbAlterar.setEnabled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbImprimir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir.png"))); // NOI18N
        jbImprimir.setText("Imprimir");
        jbImprimir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbImprimir.setEnabled(false);
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesLayout = new javax.swing.GroupLayout(jpBotoes);
        jpBotoes.setLayout(jpBotoesLayout);
        jpBotoesLayout.setHorizontalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpBotoesLayout.setVerticalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        if (jtfUsuario.getText().isEmpty() || jtfAssuntoEdital.getText().isEmpty() || jtfDestinatarioEdital.getText().isEmpty() || jtfDepartamentoDestinatarioEdital.getText().isEmpty()) {

            iniciaClasseGeral();
            classeGeral.msgAtencao("Preencha os campos 'Assunto', 'Destinatário' e 'Departamento'!");

        } else { 
            
            if (opcao.equals("salvar")) {

                verificaNumeroEdital();
                
                if (!editalVerificado.isEmpty()) {
                    iniciaClasseGeral();
                    classeGeral.msgAtencao("Esse Número já foi cadastrado! \n Cancele o Documento para gerar outro Número!");
                } else {
                    
                    salvar();
                    opcao = "salvar";
                    
                }

            } else if (opcao.equals("alterar")) {

                atualizar();

                opcao = "salvar";

            }
            
        }
        
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        if (jdbe == null) {
            jdbe = new JdBuscaEdital(null, true);
        }

        jdbe.setCodigoUsuario(codigoUsuario);
        jdbe.setVisible(true);

        setEditalBuscado(jdbe.getEdital());
        jdbe.setEdital();

        jrbEdital.transferFocus();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed

        abilitaCampos();

        jbAlterar.setEnabled(false);

        opcao = "alterar";

        jbSalvar.setEnabled(true);
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed
        
        iniciaClasseGeral();
        classeGeral.msgAtencao("Atenção, Opção de Impressão ainda não disponivel!");
        
    }//GEN-LAST:event_jbImprimirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fechar();
    }//GEN-LAST:event_formWindowClosing

    private void jtfAssuntoEditalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfAssuntoEditalFocusLost
        
        if (!jtfAssuntoEdital.getText().isEmpty()) {
            jtfAssuntoEdital.setText(jtfAssuntoEdital.getText().toUpperCase());
        }
        
    }//GEN-LAST:event_jtfAssuntoEditalFocusLost

    private void jtfDestinatarioEditalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDestinatarioEditalFocusLost
        
        if (!jtfDestinatarioEdital.getText().isEmpty()) {
            jtfDestinatarioEdital.setText(jtfDestinatarioEdital.getText().toUpperCase());
        }
        
    }//GEN-LAST:event_jtfDestinatarioEditalFocusLost

    private void jtfDepartamentoDestinatarioEditalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDepartamentoDestinatarioEditalFocusLost
        
        if (!jtfDepartamentoDestinatarioEdital.getText().isEmpty()) {
            jtfDepartamentoDestinatarioEdital.setText(jtfDepartamentoDestinatarioEdital.getText().toUpperCase());
        }
        
    }//GEN-LAST:event_jtfDepartamentoDestinatarioEditalFocusLost

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfEdital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfEdital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfEdital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfEdital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /*
         * Create and display the form
         */
        /*java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new jfEdital().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooserSolicitacao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlbAnoEdital;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JRadioButton jrbEdital;
    private javax.swing.JTextField jtfAssuntoEdital;
    private javax.swing.JTextField jtfDepartamentoDestinatarioEdital;
    private javax.swing.JTextField jtfDestinatarioEdital;
    private javax.swing.JTextField jtfNumeroEdital;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables

//Outros Metodos ===========================================================================================================================================
    public void fechar() {

        /*if (!jtfUsuario.getText().equals(nomeUsuario) || !jtfNumeroOficio.getText().equals("0")) {

        JOptionPane.showMessageDialog(null, "Cancele ou Salve o Agendamento em Edição!", "Atenção", JOptionPane.WARNING_MESSAGE, null);

        } else {*/
        dao = null;
        this.dispose();
        //}
    }

    public void cancelar() {

        iniciaControleUsuario();
        
        modeloEdital = "EDITAL";
        jtfUsuario.setText(controleUsuario.getNomeUsuario(codigoUsuario));
        jrbEdital.setSelected(true);
        preencheNumeroEdital();
        jDateChooserSolicitacao.setDate(getDateHoje());
        jtfAssuntoEdital.setText("");
        jtfDestinatarioEdital.setText("");
        jtfDepartamentoDestinatarioEdital.setText("");

        abilitaCampos();

        desabilitaBotoes();

        opcao = "salvar";
        codigo = 0;

    }

    public void abilitaCampos() {

        jrbEdital.setEnabled(true);
        jDateChooserSolicitacao.setEnabled(true);
        jtfAssuntoEdital.setEditable(true);
        jtfDestinatarioEdital.setEditable(true);
        jtfDepartamentoDestinatarioEdital.setEditable(true);

    }

    public void desabilitaCampos() {

        jrbEdital.setEnabled(false);
        jDateChooserSolicitacao.setEnabled(false);
        jtfAssuntoEdital.setEditable(false);
        jtfDestinatarioEdital.setEditable(false);
        jtfDepartamentoDestinatarioEdital.setEditable(false);

    }

    public void bloqueiaCampos() {

        jtfUsuario.setEditable(false);
        jtfNumeroEdital.setEditable(false);
    }

    public void abilitaBotoes() {

        jbCancelar.setEnabled(true);
        jbBuscar.setEnabled(true);
        jbImprimir.setEnabled(true);

        if (gerarNumeracao == true) {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(true);
            jbAlterar.setEnabled(true);
        } else {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        }

    }

    public void desabilitaBotoes() {

        jbCancelar.setEnabled(true);
        jbBuscar.setEnabled(true);
        jbImprimir.setEnabled(false);

        if (gerarNumeracao == true) {
            jbSalvar.setEnabled(true);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        } else {
            jbSalvar.setEnabled(false);
            jbExcluir.setEnabled(false);
            jbAlterar.setEnabled(false);
        }

    }

    public void preencheNumeroEdital() {

        iniciaDao();

        jtfNumeroEdital.setText("" + dao.getNumeroEdital(modeloEdital, versao.getAno(), TIPOEDITAL));

    }

    public void run() {

        for (int i = 0; i == 0; i = 0) {
            try {
                //atualizaNumeroOficio();
                if (opcao.equals("salvar")) {
                    preencheNumeroEdital();
                }

                threadAtualizaNumeroEdital.sleep(10000);

                //this.finalize();
            } catch (Throwable ex) {
                //Logger.getLogger(AtualizaNumeroOficios.class.getName()).log(Level.SEVERE, null, ex);
                except.setMensagemErro("Não foi possivel atualizar o número do Edital!");
            }
        }

    }

//Geradores, Validadores===========================================================================================================================================
    public void iniciaClasseGeral() {
        
        if (classeGeral == null) {
            classeGeral = new ClasseGeral();
        }
        
    }
    
    public void iniciaControleUsuario() {
        
        if (controleUsuario == null) {
            controleUsuario = new ControleUsuario();
        }
        
    }
    
    public void iniciaDao() {

        if (dao == null) {
            dao = new DAO();
        }

    }
    
    public void iniciaEdital() {
        
        if (edital == null) {
            edital = new Edital();
        }
        
    }
    
    public void iniciaLog() {
        
        if (geraLog == null) {
            geraLog = new Log();
        }
        
    }
    
    public void iniciaUsuario() {
        
        if (usuario == null) {
            usuario = new Usuario();
        }
        
    }
    
    public void verificaNumeroEdital() {

        iniciaDao();

        editalVerificado = dao.verificarEdital(modeloEdital, Integer.valueOf(jtfNumeroEdital.getText()), TIPOEDITAL, versao.getAno());

    }

//Getters and Setters===========================================================================================================================================
    public Date getDateHoje() {

        GregorianCalendar calendar = new GregorianCalendar();
        Date data = calendar.getTime();

        return data;

    }

    public String getAno() {

        return "Ano de " + versao.getAno();

    }

    public void setNumeroCaracteres() {
        jtfAssuntoEdital.setDocument(new FixedLengthDocument(240));
        jtfDestinatarioEdital.setDocument(new FixedLengthDocument(120));
        jtfDepartamentoDestinatarioEdital.setDocument(new FixedLengthDocument(120));
    }

    public void setEditalBuscado(Edital editalBuscado) {

        if (editalBuscado == null) {
        } else {
            
            iniciaEdital();
            iniciaUsuario();
            
            if (editalBuscado.getModeloEdital().equals("EDITAL")) {
                jrbEdital.setSelected(true);
                preencheNumeroEdital();
            } 

            usuario = (Usuario) editalBuscado.getUsuario();
            jtfUsuario.setText(usuario.getNomeUsuario());
            usuario = null;
            
            jtfNumeroEdital.setText("" + editalBuscado.getNumero());
            jDateChooserSolicitacao.setDate(editalBuscado.getDataSolicitacao());
            jtfAssuntoEdital.setText(editalBuscado.getAssuntoEdital());
            jtfDestinatarioEdital.setText(editalBuscado.getDestinatarioEdital());
            jtfDepartamentoDestinatarioEdital.setText(editalBuscado.getDepartamentoDestinatario());

            codigo = editalBuscado.getCodigoEdital();//para testar comando excluir
            edital = editalBuscado;
            edital.setCodigoEdital(codigo);

            opcao = "alterar";

            desabilitaCampos();

            abilitaBotoes();

        }
    }

    public int getCodigoUsuario() {
        return codigoUsuario;
    }

    public void setCodigoUsuario(int codigoUsuario) {
        iniciaControleUsuario();
        jtfUsuario.setText(controleUsuario.getNomeUsuario(codigoUsuario));
        this.codigoUsuario = codigoUsuario;
        getPermissoes();
        desabilitaBotoes();
        setNumeroCaracteres();
    }

    public void getPermissoes() {
        Permissoes permissoes;
        iniciaDao();
        //DAO dao = new DAO();

        permissoes = (Permissoes) dao.buscaPermissoes(getCodigoUsuario());

        gerarNumeracao = permissoes.isGerarNumeracaoEditais();
    }

//Metodos DAO===========================================================================================================================================
    public void salvar() {

        if (!jtfUsuario.getText().isEmpty() && !jtfNumeroEdital.getText().isEmpty() && jDateChooserSolicitacao.getDate() != null) {

            iniciaDao();
            iniciaEdital();
            iniciaUsuario();

            edital.setAno(versao.getAno());
            edital.setDataSolicitacao(jDateChooserSolicitacao.getDate());
            edital.setNumero(Integer.parseInt(jtfNumeroEdital.getText()));
            
            usuario = (Usuario) dao.buscaUsuario(0, jtfUsuario.getText().toString(), "");
            edital.setUsuario(usuario);
            
            edital.setTipoEdital(TIPOEDITAL);
            edital.setAssuntoEdital(jtfAssuntoEdital.getText());
            edital.setDepartamentoDestinatario(jtfDepartamentoDestinatarioEdital.getText());
            
            edital.setDestinatarioEdital(jtfDestinatarioEdital.getText());
            if (jrbEdital.isSelected() == true) {
                edital.setModeloEdital(modeloEdital);
            } 

            try {
                iniciaLog();
                geraLog.criaLog(codigoUsuario, "Edital", "Tentou Salvar Nº: " + jtfNumeroEdital.getText() + " Assunto: " + jtfAssuntoEdital.getText() + " Destinatário: " + jtfDestinatarioEdital.getText());
            } catch (IOException ex) {
                Logger.getLogger(JfPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            dao.inserir(edital, 7, codigoUsuario);
            cancelar();

        } else {
            iniciaClasseGeral();
            classeGeral.msgAtencao("Complete os Campos Obrigatórios, destacados em Azul!");
        }

    }

    public void atualizar() {

        if (!jtfUsuario.getText().isEmpty() && !jtfNumeroEdital.getText().isEmpty() && jDateChooserSolicitacao.getDate() != null) {

            iniciaDao();
            iniciaEdital();
            iniciaUsuario();

            edital.setAno(versao.getAno());
            edital.setDataSolicitacao(jDateChooserSolicitacao.getDate());
            edital.setNumero(Integer.parseInt(jtfNumeroEdital.getText()));
            
            usuario = (Usuario) dao.buscaUsuario(0, jtfUsuario.getText().toString(), "");
            edital.setUsuario(usuario);
            
            edital.setTipoEdital(TIPOEDITAL);
            edital.setAssuntoEdital(jtfAssuntoEdital.getText());
            edital.setDepartamentoDestinatario(jtfDepartamentoDestinatarioEdital.getText());
            
            edital.setDestinatarioEdital(jtfDestinatarioEdital.getText());
            if (jrbEdital.isSelected() == true) {
                edital.setModeloEdital(modeloEdital);
            }

            try {
                iniciaLog();
                geraLog.criaLog(codigoUsuario, "Edital", "Tentou Alterar Nº: " + jtfNumeroEdital.getText() + " Assunto: " + jtfAssuntoEdital.getText() + " Destinatário: " + jtfDestinatarioEdital.getText());
            } catch (IOException ex) {
                Logger.getLogger(JfPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            dao.atualizar(edital, 7, codigoUsuario);
            cancelar();

        } else {
            iniciaClasseGeral();
            classeGeral.msgAtencao("Complete os Campos Obrigatórios, destacados em Azul!");
        }

    }

    public void excluir() {

        iniciaClasseGeral();

        if (classeGeral.msgConfirma("Deseja excluir o Edital?")) {

            iniciaDao();
            iniciaEdital();
            
            try {
                iniciaLog();
                geraLog.criaLog(codigoUsuario, "Edital", "Tentou Excluir Nº: " + jtfNumeroEdital.getText() + " Assunto: " + jtfAssuntoEdital.getText() + " Destinatário: " + jtfDestinatarioEdital.getText());
            } catch (IOException ex) {
                Logger.getLogger(JfPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            dao.excluir(edital, codigoUsuario);
            cancelar();

        }

    }

}
