/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import conexao.Conexao;
import controlador.ClasseGeral;
import controlador.ControleVersao;
import controlador.FixedLengthDocument;
import controlador.ValidaData;
import dao.DAO;
import excecoes.ExcCadastro;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.CrachasComae;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author luizam
 */
public class JfImpressosCrachaComae extends javax.swing.JFrame {

    private static ControleVersao versao = new ControleVersao();
    private ClasseGeral classeGeral;
    private CrachasComae crachasComae;
    private DAO dao;
    private ValidaData validaData;
    
    private JasperPrint jPrint;
    private JasperViewer jViewer;
    private JdBuscaCrachasComae jdbcc;
    
    private int codigo;
    private int codigoUsuario;
    private String opcao = "salvar";

    /**
     * Creates new form JfImpressosCracha
     */
    public JfImpressosCrachaComae() {
        super("Impressos Crachá COMAE - " + versao.getVersao() + " - " + versao.getAno());
        initComponents();

        //Altera icone na barra de titulo
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage("C:/SURGI/imagens/SURGI32x32.png");
        this.setIconImage(img);

        //centraliza tela
        setSize(getWidth(), getHeight());
        setLocationRelativeTo(null);

        setNumeroCaracteres();

        desabilitaBotoes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBotoes = new javax.swing.JPanel();
        jbImprimir = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jpImpressosCracha = new javax.swing.JPanel();
        jpCracha01 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNomeCracha = new javax.swing.JTextField();
        jtfRepresentacaoCracha = new javax.swing.JTextField();
        jtfCargoCracha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jpCracha02 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtfNomeCracha2 = new javax.swing.JTextField();
        jtfRepresentacaoCracha2 = new javax.swing.JTextField();
        jtfCargoCracha2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpCracha3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtfNomeCracha3 = new javax.swing.JTextField();
        jtfRepresentacaoCracha3 = new javax.swing.JTextField();
        jtfCargoCracha3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpCracha4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jtfNomeCracha4 = new javax.swing.JTextField();
        jtfRepresentacaoCracha4 = new javax.swing.JTextField();
        jtfCargoCracha4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbImpresso = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooserDataCracha = new com.toedter.calendar.JDateChooser();
        jDateChooserDataEntrega = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpBotoes.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jbImprimir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir.png"))); // NOI18N
        jbImprimir.setText("Imprimir");
        jbImprimir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/OK.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbAlterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reload.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesLayout = new javax.swing.GroupLayout(jpBotoes);
        jpBotoes.setLayout(jpBotoesLayout);
        jpBotoesLayout.setHorizontalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jpBotoesLayout.setVerticalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jpImpressosCracha.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        jpCracha01.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crachá 01", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome: ");

        jtfNomeCracha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfNomeCracha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfRepresentacaoCracha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfRepresentacaoCracha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfCargoCracha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfCargoCracha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Cargo: ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Representação: ");

        javax.swing.GroupLayout jpCracha01Layout = new javax.swing.GroupLayout(jpCracha01);
        jpCracha01.setLayout(jpCracha01Layout);
        jpCracha01Layout.setHorizontalGroup(
            jpCracha01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCracha01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCracha01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCracha01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNomeCracha, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRepresentacaoCracha, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCargoCracha, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpCracha01Layout.setVerticalGroup(
            jpCracha01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCracha01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCracha01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNomeCracha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCracha01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCargoCracha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpCracha01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtfRepresentacaoCracha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpCracha02.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crachá 02", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Nome: ");

        jtfNomeCracha2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfNomeCracha2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfRepresentacaoCracha2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfRepresentacaoCracha2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfCargoCracha2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfCargoCracha2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Cargo: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Representação: ");

        javax.swing.GroupLayout jpCracha02Layout = new javax.swing.GroupLayout(jpCracha02);
        jpCracha02.setLayout(jpCracha02Layout);
        jpCracha02Layout.setHorizontalGroup(
            jpCracha02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCracha02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCracha02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCracha02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNomeCracha2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRepresentacaoCracha2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCargoCracha2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpCracha02Layout.setVerticalGroup(
            jpCracha02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCracha02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCracha02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfNomeCracha2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCracha02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfCargoCracha2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCracha02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfRepresentacaoCracha2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpCracha3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crachá 03", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Nome: ");

        jtfNomeCracha3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfNomeCracha3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfRepresentacaoCracha3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfRepresentacaoCracha3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfCargoCracha3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfCargoCracha3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Cargo: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Representação: ");

        javax.swing.GroupLayout jpCracha3Layout = new javax.swing.GroupLayout(jpCracha3);
        jpCracha3.setLayout(jpCracha3Layout);
        jpCracha3Layout.setHorizontalGroup(
            jpCracha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCracha3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCracha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCracha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNomeCracha3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRepresentacaoCracha3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCargoCracha3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpCracha3Layout.setVerticalGroup(
            jpCracha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCracha3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCracha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfNomeCracha3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCracha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtfCargoCracha3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCracha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfRepresentacaoCracha3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpCracha4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crachá 04", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Nome: ");

        jtfNomeCracha4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfNomeCracha4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfRepresentacaoCracha4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfRepresentacaoCracha4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jtfCargoCracha4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfCargoCracha4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Cargo: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Representação: ");

        javax.swing.GroupLayout jpCracha4Layout = new javax.swing.GroupLayout(jpCracha4);
        jpCracha4.setLayout(jpCracha4Layout);
        jpCracha4Layout.setHorizontalGroup(
            jpCracha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCracha4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCracha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCracha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNomeCracha4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRepresentacaoCracha4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCargoCracha4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpCracha4Layout.setVerticalGroup(
            jpCracha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCracha4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCracha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtfNomeCracha4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCracha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtfCargoCracha4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCracha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfRepresentacaoCracha4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Já foi impresso: ");

        jcbImpresso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbImpresso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NÃO", "SIM" }));
        jcbImpresso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Data entrega: ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Data impressão: ");

        jDateChooserDataCracha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jDateChooserDataEntrega.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jpImpressosCrachaLayout = new javax.swing.GroupLayout(jpImpressosCracha);
        jpImpressosCracha.setLayout(jpImpressosCrachaLayout);
        jpImpressosCrachaLayout.setHorizontalGroup(
            jpImpressosCrachaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImpressosCrachaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpImpressosCrachaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpImpressosCrachaLayout.createSequentialGroup()
                        .addComponent(jpCracha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpCracha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpImpressosCrachaLayout.createSequentialGroup()
                        .addGroup(jpImpressosCrachaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpImpressosCrachaLayout.createSequentialGroup()
                                .addComponent(jpCracha01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpCracha02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpImpressosCrachaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbImpresso, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserDataCracha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpImpressosCrachaLayout.setVerticalGroup(
            jpImpressosCrachaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImpressosCrachaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpImpressosCrachaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpCracha01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCracha02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpImpressosCrachaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpCracha4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCracha3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpImpressosCrachaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(jDateChooserDataCracha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jcbImpresso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooserDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpImpressosCracha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpImpressosCracha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed

        Conexao conexao = new Conexao();
        HashMap parametros = new HashMap();
        iniciaValidaData();
        
        try {

            parametros.put("codigoCrachaComae", codigo);
            
            conexao.getConexao();

        } catch (ExcCadastro ex) {
            Logger.getLogger(JfImpressosCmei.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {

            if (!jtfNomeCracha.getText().isEmpty() || !jtfNomeCracha2.getText().isEmpty() || !jtfNomeCracha3.getText().isEmpty() || !jtfNomeCracha4.getText().isEmpty()) {
                System.out.println("" + codigo);
                jPrint = JasperFillManager.fillReport("ImpressaoCrachaComae.jasper", parametros, conexao.getConexao());

            }

            jDateChooserDataCracha.setDate(validaData.getDateAtual());
            jcbImpresso.setSelectedIndex(1);
            
            if (jPrint != null) {
                jViewer = new JasperViewer(jPrint, false);
                jViewer.setVisible(true);
                jPrint = null;
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbImprimirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fechar();
    }//GEN-LAST:event_formWindowClosing

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        
        if (jdbcc == null) {
            jdbcc = new JdBuscaCrachasComae(null, true);
        }
        
        jdbcc.setCodigoUsuario(codigoUsuario);
        jdbcc.setVisible(true);
        
        setCrachasBuscados(jdbcc.getCrachasComae());
        jdbcc.setCrachasComae();
        
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        
        if (((!jtfCargoCracha.getText().isEmpty() || !jtfRepresentacaoCracha.getText().isEmpty()) && !jtfNomeCracha.getText().isEmpty()) ||
                ((!jtfCargoCracha2.getText().isEmpty() || !jtfRepresentacaoCracha2.getText().isEmpty()) && !jtfNomeCracha2.getText().isEmpty()) ||
                ((!jtfCargoCracha3.getText().isEmpty() || !jtfRepresentacaoCracha3.getText().isEmpty()) && !jtfNomeCracha3.getText().isEmpty()) ||
                ((!jtfCargoCracha4.getText().isEmpty() || !jtfRepresentacaoCracha4.getText().isEmpty()) && !jtfNomeCracha4.getText().isEmpty())
                ) {
            
            if (opcao.equals("salvar")) {
                salvar();
                opcao = "salvar";
            } else {
                atualizar();
                opcao = "salvar";
            }
            
        } else {
            
            iniciaClasseGeral();
            classeGeral.msgAtencao("Preencha os campos de Nome, e Cargo ou Departamento, para impressão do crachá!");
            
        }
        
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        
        habilitaCampos();

        jbAlterar.setEnabled(false);

        opcao = "alterar";

        jbSalvar.setEnabled(true);
        
    }//GEN-LAST:event_jbAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfImpressosCracha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfImpressosCracha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfImpressosCracha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfImpressosCracha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfImpressosCracha().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooserDataCracha;
    private com.toedter.calendar.JDateChooser jDateChooserDataEntrega;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox jcbImpresso;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpCracha01;
    private javax.swing.JPanel jpCracha02;
    private javax.swing.JPanel jpCracha3;
    private javax.swing.JPanel jpCracha4;
    private javax.swing.JPanel jpImpressosCracha;
    private javax.swing.JTextField jtfCargoCracha;
    private javax.swing.JTextField jtfCargoCracha2;
    private javax.swing.JTextField jtfCargoCracha3;
    private javax.swing.JTextField jtfCargoCracha4;
    private javax.swing.JTextField jtfNomeCracha;
    private javax.swing.JTextField jtfNomeCracha2;
    private javax.swing.JTextField jtfNomeCracha3;
    private javax.swing.JTextField jtfNomeCracha4;
    private javax.swing.JTextField jtfRepresentacaoCracha;
    private javax.swing.JTextField jtfRepresentacaoCracha2;
    private javax.swing.JTextField jtfRepresentacaoCracha3;
    private javax.swing.JTextField jtfRepresentacaoCracha4;
    // End of variables declaration//GEN-END:variables

//Outros Metodos=============================================================================================================================================================
    public void fechar() {
        cancelar();
        this.dispose();
    }

    public void cancelar() {

        jtfRepresentacaoCracha.setText("");
        jtfRepresentacaoCracha2.setText("");
        jtfRepresentacaoCracha3.setText("");
        jtfRepresentacaoCracha4.setText("");
        jtfCargoCracha.setText("");
        jtfCargoCracha2.setText("");
        jtfCargoCracha3.setText("");
        jtfCargoCracha4.setText("");
        jtfNomeCracha.setText("");
        jtfNomeCracha2.setText("");
        jtfNomeCracha3.setText("");
        jtfNomeCracha4.setText("");
        jcbImpresso.setSelectedIndex(0);
        jDateChooserDataCracha.setDate(null);
        jDateChooserDataEntrega.setDate(null);

        habilitaCampos();
        desabilitaBotoes();
        
        opcao = "salvar";
        
    }

    public void habilitaBotoes() {
        
        jbAlterar.setEnabled(true);
        jbBuscar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbImprimir.setEnabled(true);
        jbSalvar.setEnabled(false);
        
    }
    
    public void desabilitaBotoes() {
        
        jbAlterar.setEnabled(false);
        jbBuscar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbImprimir.setEnabled(false);
        jbSalvar.setEnabled(true);
        
    }
    
    public void habilitaCampos() {
        
        jtfRepresentacaoCracha.setEditable(true);
        jtfRepresentacaoCracha2.setEditable(true);
        jtfRepresentacaoCracha3.setEditable(true);
        jtfRepresentacaoCracha4.setEditable(true);
        jtfCargoCracha.setEditable(true);
        jtfCargoCracha2.setEditable(true);
        jtfCargoCracha3.setEditable(true);
        jtfCargoCracha4.setEditable(true);
        jtfNomeCracha.setEditable(true);
        jtfNomeCracha2.setEditable(true);
        jtfNomeCracha3.setEditable(true);
        jtfNomeCracha4.setEditable(true);
        jcbImpresso.setEnabled(true);
        jDateChooserDataCracha.setEnabled(true);
        jDateChooserDataEntrega.setEnabled(true);
        
    }
    
    public void desabilitaCampos() {
        
        jtfRepresentacaoCracha.setEditable(false);
        jtfRepresentacaoCracha2.setEditable(false);
        jtfRepresentacaoCracha3.setEditable(false);
        jtfRepresentacaoCracha4.setEditable(false);
        jtfCargoCracha.setEditable(false);
        jtfCargoCracha2.setEditable(false);
        jtfCargoCracha3.setEditable(false);
        jtfCargoCracha4.setEditable(false);
        jtfNomeCracha.setEditable(false);
        jtfNomeCracha2.setEditable(false);
        jtfNomeCracha3.setEditable(false);
        jtfNomeCracha4.setEditable(false);
        jcbImpresso.setEnabled(false);
        jDateChooserDataCracha.setEnabled(false);
        jDateChooserDataEntrega.setEnabled(false);
        
    }
    
//Geradores, Validadores===========================================================================================================================================
    public void iniciaClasseGeral() {
        
        if (classeGeral == null) {
            classeGeral = new ClasseGeral();
        }

    }
    
    public void iniciaCrachasComae() {
        
        if (crachasComae == null) {
            crachasComae = new CrachasComae();
        }
        
    }
    
    public void iniciaDao() {
        
        if (dao == null) {
            dao = new DAO();
        }
        
    }
   
    public void iniciaValidaData() {
        
        if (validaData == null) {
            validaData = new ValidaData();
        }
        
    }
    
//Getters and Setters===========================================================================================================================================
    public void setCodigoUsuario(int codigoUsuario) {
        this.codigoUsuario = codigoUsuario; 
    }
    
    public void setCrachasBuscados(CrachasComae crachasComaeBuscados) {
        
        if (crachasComaeBuscados == null) {
            
        } else {
            
            iniciaCrachasComae();
        
            jtfRepresentacaoCracha.setText(crachasComaeBuscados.getRepresentacao1());
            jtfRepresentacaoCracha2.setText(crachasComaeBuscados.getRepresentacao2());
            jtfRepresentacaoCracha3.setText(crachasComaeBuscados.getRepresentacao3());
            jtfRepresentacaoCracha4.setText(crachasComaeBuscados.getRepresentacao4());
            jtfCargoCracha.setText(crachasComaeBuscados.getCargoCracha1());
            jtfCargoCracha2.setText(crachasComaeBuscados.getCargoCracha2());
            jtfCargoCracha3.setText(crachasComaeBuscados.getCargoCracha3());
            jtfCargoCracha4.setText(crachasComaeBuscados.getCargoCracha4());
            jtfNomeCracha.setText(crachasComaeBuscados.getNomeCracha1());
            jtfNomeCracha2.setText(crachasComaeBuscados.getNomeCracha2());
            jtfNomeCracha3.setText(crachasComaeBuscados.getNomeCracha3());
            jtfNomeCracha4.setText(crachasComaeBuscados.getNomeCracha4());
            jDateChooserDataCracha.setDate(crachasComaeBuscados.getDataCracha());
            jDateChooserDataEntrega.setDate(crachasComaeBuscados.getDataEntrega());
            
            
            if (crachasComaeBuscados.isImpresso()) {
                jcbImpresso.setSelectedIndex(1);
            } else {
                jcbImpresso.setSelectedIndex(0);
            }
        
            codigo = crachasComaeBuscados.getCodigoCrachaComae();
            crachasComaeBuscados.setCodigoCrachaComae(codigo);
        
            desabilitaCampos();
            habilitaBotoes();
            
        }
        
    }
    
    public void setNumeroCaracteres() {

        jtfRepresentacaoCracha.setDocument(new FixedLengthDocument(30));
        jtfRepresentacaoCracha2.setDocument(new FixedLengthDocument(30));
        jtfRepresentacaoCracha3.setDocument(new FixedLengthDocument(30));
        jtfRepresentacaoCracha4.setDocument(new FixedLengthDocument(30));
        jtfCargoCracha.setDocument(new FixedLengthDocument(30));
        jtfCargoCracha2.setDocument(new FixedLengthDocument(30));
        jtfCargoCracha3.setDocument(new FixedLengthDocument(30));
        jtfCargoCracha4.setDocument(new FixedLengthDocument(30));
        jtfNomeCracha.setDocument(new FixedLengthDocument(18));
        jtfNomeCracha2.setDocument(new FixedLengthDocument(18));
        jtfNomeCracha3.setDocument(new FixedLengthDocument(18));
        jtfNomeCracha4.setDocument(new FixedLengthDocument(18));

    }
    
//Metodos DAO===========================================================================================================================================
    public void salvar() {
        
        iniciaDao();
        iniciaCrachasComae();
       
        crachasComae.setCargoCracha1(jtfCargoCracha.getText());
        crachasComae.setCargoCracha2(jtfCargoCracha2.getText());
        crachasComae.setCargoCracha3(jtfCargoCracha3.getText());
        crachasComae.setCargoCracha4(jtfCargoCracha4.getText());
        crachasComae.setDataCracha(jDateChooserDataCracha.getDate());
        crachasComae.setDataEntrega(jDateChooserDataEntrega.getDate());
        crachasComae.setRepresentacao1(jtfRepresentacaoCracha.getText());
        crachasComae.setRepresentacao2(jtfRepresentacaoCracha2.getText());
        crachasComae.setRepresentacao3(jtfRepresentacaoCracha3.getText());
        crachasComae.setRepresentacao4(jtfRepresentacaoCracha4.getText());
        
        if (jcbImpresso.getSelectedIndex() == 0) {
            crachasComae.setImpresso(false);
        } else {
            crachasComae.setImpresso(true);
        }
        
        crachasComae.setNomeCracha1(jtfNomeCracha.getText());
        crachasComae.setNomeCracha2(jtfNomeCracha2.getText());
        crachasComae.setNomeCracha3(jtfNomeCracha3.getText());
        crachasComae.setNomeCracha4(jtfNomeCracha4.getText());
        
        dao.inserir(crachasComae, 7, codigoUsuario);
        cancelar();
        
    }
    
    public void atualizar() {
        
        iniciaDao();
        iniciaCrachasComae();
       
        crachasComae.setCargoCracha1(jtfCargoCracha.getText());
        crachasComae.setCargoCracha2(jtfCargoCracha2.getText());
        crachasComae.setCargoCracha3(jtfCargoCracha3.getText());
        crachasComae.setCargoCracha4(jtfCargoCracha4.getText());
        crachasComae.setCodigoCrachaComae(codigo);
        crachasComae.setDataCracha(jDateChooserDataCracha.getDate());
        crachasComae.setDataEntrega(jDateChooserDataEntrega.getDate());
        crachasComae.setRepresentacao1(jtfRepresentacaoCracha.getText());
        crachasComae.setRepresentacao2(jtfRepresentacaoCracha2.getText());
        crachasComae.setRepresentacao3(jtfRepresentacaoCracha3.getText());
        crachasComae.setRepresentacao4(jtfRepresentacaoCracha4.getText());
        
        if (jcbImpresso.getSelectedIndex() == 0) {
            crachasComae.setImpresso(false);
        } else {
            crachasComae.setImpresso(true);
        }
        
        crachasComae.setNomeCracha1(jtfNomeCracha.getText());
        crachasComae.setNomeCracha2(jtfNomeCracha2.getText());
        crachasComae.setNomeCracha3(jtfNomeCracha3.getText());
        crachasComae.setNomeCracha4(jtfNomeCracha4.getText());
        
        dao.atualizar(crachasComae, 7, codigoUsuario);
        cancelar();
        
    }
    
}
